/**
 * Shared types used by DynamicGameState
 */

export type AgentId = "keeper" | "memory" | "action";

export type Phase = "intro" | "investigation" | "confrontation" | "downtime";

export type ActionType =
  | "exploration" // Discovering clues, understanding environment, gathering information
  | "social" // Influencing NPCs, gathering intelligence, reaching consensus
  | "stealth" // Acting without being detected
  | "combat" // Causing damage, subduing or stopping opponents
  | "chase" // Extending or closing distance
  | "mental" // Withstanding or resisting psychological shock
  | "environmental" // Confronting environment and physiological limits
  | "narrative"; // Making key choices

export interface ActionAnalysis {
  character: string;
  action: string;
  actionType: ActionType;
  target: {
    name: string | null;
    intent: string;
  };
  requiresSkillSelection?: boolean; // Whether player needs to select a skill (frontend will use RAG to suggest skills)
}

export type NPCResponseType =
  | "none" // No response
  | ActionType; // One of the eight action types

export interface NPCResponseAnalysis {
  npcName: string;
  willRespond: boolean; // Whether the NPC will respond
  responseType: NPCResponseType | null; // Type of response if willRespond is true (one of the eight action types, or "none")
  responseDescription: string; // Description of what the NPC will do
  executionOrder: number; // Execution order (1, 2, 3, 4...) - determines the sequence of NPC actions
  targetCharacter?: string | null; // Target character if response is directed
}

export interface SceneChangeRequest {
  shouldChange: boolean; // Whether scene change is needed
  targetSceneName: string | null; // Target scene name (generated by LLM)
  reason: string; // Reason for scene change
  timestamp: Date; // Request time
}

export interface SceneTransitionRejection {
  wasRequested: boolean; // Whether scene transition request was rejected
  reasoning: string; // Director's reason for rejection
  timestamp: Date; // Rejection time
}

/**
 * Game ending information determined by Director Agent
 */
export interface GameEndingInfo {
  isEnded: boolean; // Whether the game has ended
  endingType: "death" | "time_limit" | "victory" | "failure" | "other"; // Type of ending
  reason: string; // Why the game ended (2-3 sentences explaining the ending)
  timestamp: Date; // When the game ended
}

export interface VisitedScenarioBasic {
  id: string;
  name: string;
  location: string;
}

/**
 * Detailed information about a discovered clue
 */
export interface DiscoveredClue {
  /** Clue text content */
  text: string;
  /** Clue type: scenario clue, NPC clue, or secret */
  type: "scenario" | "npc" | "secret";
  /** Source name (scenario name or NPC name) */
  sourceName: string;
  /** Who discovered this clue */
  discoveredBy: string;
  /** When discovered (ISO format) */
  discoveredAt: string;
  /** Clue category (scenario clues only) */
  category?:
    | "physical"
    | "witness"
    | "document"
    | "environment"
    | "knowledge"
    | "observation";
  /** Clue difficulty (scenario clues only) */
  difficulty?: "automatic" | "regular" | "hard" | "extreme";
  /** Discovery method */
  method?: string;
}

export type TimeConsumption = "instant" | "short" | "scene";

export interface DirectorDecision {
  shouldProgress: boolean;
  targetSnapshotId?: string; // Specific scene snapshot ID to progress to
  estimatedShortActions?: number | null; // Estimated number of short actions executable in target scene
  increaseShortActionCapBy?: number | null; // When not progressing, increase current scene short action cap
  reasoning: string; // Reason for progression
  timestamp: Date; // Decision time
}

/** Structured dice roll info for frontend display (character, skill, penalty) */
export interface DiceRollInfo {
  character: string; // Who rolled (player or NPC name)
  roll: string; // Original roll string e.g. "Investigator John: 1d100[0]: 67 (Brawling 50% = failure)"
  skill?: string; // Extracted skill e.g. "Brawling 50%"
  success?: "success" | "failure" | "critical" | "fumble"; // For skill checks
  penalty?: string; // e.g. "penalty die", "-20", "bonus die"
}

export interface ActionResult {
  timestamp: Date;
  gameTime: string;
  timeElapsedMinutes?: number; // Actual minutes consumed by the action
  location: string;
  character: string;
  result: string;
  diceRolls: string[];
  timeConsumption: TimeConsumption; // Time consumption type of this action
  scenarioChanges?: string[]; // List of permanent changes made to the scenario
}

/** Build DiceRollInfo[] from action results for frontend display
 * Splits multi-dice rolls (e.g., with penalty/bonus) into separate entries for animation
 */
export function buildDiceRollInfos(
  actionResults: ActionResult[],
  options?: {
    opposedRollCharacter?: string | null;
  }
): DiceRollInfo[] {
  const infos: DiceRollInfo[] = [];
  const opposedRollCharacter = options?.opposedRollCharacter?.trim() || null;
  for (const result of actionResults || []) {
    const rolls = result.diceRolls || [];
    for (const roll of rolls) {
      const isOpposed = /\b1d100_opposed\[\d+\]\s*:/i.test(roll);
      const actorFromRoll = extractRollCharacter(roll);
      const rollCharacter =
        actorFromRoll ||
        (isOpposed && opposedRollCharacter
          ? opposedRollCharacter
          : result.character);

      // Check if this roll contains multiple dice (penalty/bonus format)
      // Format: "Dr. Smith: 1d100[0]: 45, 1d100[1]: 82(penalty),(Spot Hidden 60% use highest 82 = failure)"
      const diceMatches = [...roll.matchAll(/(\d+d\d+\[\d+\]:\s*\d+(?:\(penalty\)|\(bonus\))?)/gi)];

      if (diceMatches.length > 1) {
        // Multi-dice roll - create separate DiceRollInfo for each die
        for (const match of diceMatches) {
          const diceStr = match[1]; // e.g., "1d100[0]: 45" or "1d100[1]: 82(penalty)"
          const singleDiceRoll = `${rollCharacter}: ${diceStr}`;
          infos.push({
            character: rollCharacter,
            roll: singleDiceRoll,
            skill: undefined,
            success: undefined,
            penalty: diceStr.includes("(penalty)") ? "penalty" : diceStr.includes("(bonus)") ? "bonus" : undefined,
          });
        }
      } else {
        // Single dice roll - use original logic
        infos.push(parseDiceRollInfo(rollCharacter, roll));
      }
    }
  }
  return infos;
}

/** Extract actor name from roll prefix. Format: "Actor Name: 1d100[0]: ..." */
function extractRollCharacter(roll: string): string | null {
  if (!roll || typeof roll !== "string") return null;
  const diceAt = roll.search(/\b(?:1d100_opposed|\d+d\d+)\[\d+\]\s*:/i);
  if (diceAt <= 0) return null;
  const candidate = roll
    .slice(0, diceAt)
    .replace(/[:\s]+$/g, "")
    .trim();
  return candidate.length > 0 ? candidate : null;
}

/** Parse skill, success, penalty from dice roll string.
 * Supports both old and new formats:
 * - Old: "Investigator John: 1d100[0]: 67 (Brawling 50% = failure)"
 * - New: "Dr. Smith: 1d100[0]: 45, 1d100[1]: 82(penalty),(Spot Hidden 60% use highest 82 = failure)"
 */
function parseDiceRollInfo(character: string, roll: string): DiceRollInfo {
  const info: DiceRollInfo = { character, roll };

  // Match last parentheses group (often contains skill check result): "(Brawling 50% = failure)"
  const parenMatches = roll.matchAll(/\(([^)]+)\)/g);
  const allMatches = [...parenMatches];
  const content =
    allMatches.length > 0 ? allMatches[allMatches.length - 1][1] : null;
  if (!content) return info;

  // Success/failure: "= success" or "= failure" or "= critical" or "= fumble"
  const successMatch = content.match(
    /\s*=\s*(success|failure|critical|fumble)\s*$/i
  );
  if (successMatch) {
    info.success = successMatch[1].toLowerCase() as DiceRollInfo["success"];
  }

  // Penalty/Bonus detection - check entire roll string, not just last parentheses
  // New format: "1d100[1]: 82(penalty)" or "1d100[1]: 34(bonus)"
  // Old format: "(Spot Hidden 60% penalty die = failure)"
  const newFormatPenaltyMatch = roll.match(/\(penalty\)/i);
  const newFormatBonusMatch = roll.match(/\(bonus\)/i);
  const oldFormatPenaltyMatch = content.match(
    /(?:penalty\s+die|bonus\s+die|-\s*\d+\s*%?|\(\s*-\s*\d+\s*\))/i
  );

  if (newFormatPenaltyMatch) {
    info.penalty = "penalty";
  } else if (newFormatBonusMatch) {
    info.penalty = "bonus";
  } else if (oldFormatPenaltyMatch) {
    info.penalty = oldFormatPenaltyMatch[0].trim();
  }

  // Skill: part before "=" or penalty. Match "SkillName XX%" or "purpose" (damage, etc.)
  const beforeEquals = content
    .replace(/\s*=\s*(success|failure|critical|fumble)\s*$/i, "")
    .trim();
  const skillPart = beforeEquals
    .replace(
      /(?:penalty\s+die|bonus\s+die|-\s*\d+\s*%?|\(\s*-\s*\d+\s*\)|use\s+(?:highest|lowest)\s+\d+).*/gi,
      ""
    )
    .trim();
  if (skillPart && (/\d+%\s*$/.test(skillPart) || skillPart.length < 40)) {
    info.skill = skillPart;
  }
  return info;
}

export interface AgentResult {
  agentId: AgentId;
  content: string;
  timestamp: Date;
  metadata?: any;
}
