const SKILL_NAME_ZH: Record<string, string> = {
  Charm: "魅惑",
  Bluff: "欺骗",
  Intimidate: "恐吓",
  Persuade: "说服",
  Psychology: "心理学",
  Accounting: "会计",
  Anthropology: "人类学",
  Archaeology: "考古学",
  "Art and Craft": "艺术与手工",
  History: "历史",
  Law: "法律",
  Research: "检索",
  Occult: "神秘学",
  Biology: "生物学",
  Chemistry: "化学",
  Physics: "物理学",
  Appraise: "鉴定",
  Listen: "聆听",
  Perception: "侦察",
  Track: "追踪",
  Climb: "攀爬",
  Dodge: "闪避",
  Jump: "跳跃",
  Swim: "游泳",
  Throw: "投掷",
  Ride: "骑术",
  Disguise: "乔装",
  "Sleight of Hand": "巧手",
  Stealth: "潜行",
  "Electrical Repair": "电气维修",
  "Mechanical Repair": "机械维修",
  "Operate Heavy Machinery": "重型机械操作",
  "Pilot (Aircraft)": "飞机驾驶",
  "Pilot (Boat)": "船只驾驶",
  "Drive Auto": "汽车驾驶",
  Navigate: "导航",
  "First Aid": "急救",
  Medicine: "医学",
  "Natural World": "自然学",
  "Survival (Arctic)": "生存（极地）",
  "Survival (Desert)": "生存（沙漠）",
  "Survival (Forest)": "生存（森林）",
  Psychoanalysis: "精神分析",
  Brawling: "格斗",
  Sword: "剑术",
  Axe: "斧术",
  Whip: "鞭术",
  Pistol: "手枪",
  Rifle: "步枪",
  "Submachine Gun": "冲锋枪",
  Bow: "弓",
  Locksmith: "开锁",
  Criminology: "犯罪学",
  Forgery: "伪造",
  "Language (Own)": "母语",
  "Language (Other)": "外语",
  "Social Status": "社会地位",
  "Forbidden Lore": "禁忌知识",
};

export const getSkillNameZh = (name: string): string =>
  SKILL_NAME_ZH[name] ?? name;
