/**
 * Shared types used by both GameState and DynamicGameState
 * GameState-specific types are in gameState.ts
 * DynamicGameState-specific types are in dynamicworldagent/state/
 */

export type AgentId = "keeper" | "memory" | "action";

export type Phase = "intro" | "investigation" | "confrontation" | "downtime";

export type ActionType = 
  | "exploration"      // Discovering clues, understanding environment, gathering information
  | "social"          // Influencing NPCs, gathering intelligence, reaching consensus
  | "stealth"         // Acting without being detected
  | "combat"          // Causing damage, subduing or stopping opponents
  | "chase"           // Extending or closing distance
  | "mental"          // Withstanding or resisting psychological shock
  | "environmental"   // Confronting environment and physiological limits
  | "narrative";      // Making key choices

export interface ActionAnalysis {
  character: string;
  action: string;
  actionType: ActionType;
  target: {
    name: string | null;
    intent: string;
  };
  requiresDice: boolean;  // Whether dice roll is required
}

export type NPCResponseType = 
  | "none"              // No response
  | ActionType;         // One of the eight action types

export interface NPCResponseAnalysis {
  npcName: string;
  willRespond: boolean;  // Whether the NPC will respond
  responseType: NPCResponseType | null;  // Type of response if willRespond is true (one of the eight action types, or "none")
  responseDescription: string;  // Description of what the NPC will do
  executionOrder: number;  // Execution order (1, 2, 3, 4...) - determines the sequence of NPC actions
  targetCharacter?: string | null;  // Target character if response is directed
}

export interface SceneChangeRequest {
  shouldChange: boolean;        // Whether scene change is needed
  targetSceneName: string | null;  // Target scene name (generated by LLM)
  reason: string;               // Reason for scene change
  timestamp: Date;              // Request time
}

export interface SceneTransitionRejection {
  wasRequested: boolean;        // Whether scene transition request was rejected
  reasoning: string;            // Director's reason for rejection
  timestamp: Date;              // Rejection time
}

/**
 * Game ending information determined by Director Agent
 */
export interface GameEndingInfo {
  isEnded: boolean;             // Whether the game has ended
  endingType: "death" | "time_limit" | "victory" | "failure" | "other";  // Type of ending
  reason: string;               // Why the game ended (2-3 sentences explaining the ending)
  timestamp: Date;              // When the game ended
}

export interface VisitedScenarioBasic {
  id: string;
  name: string;
  location: string;
}

/**
 * Detailed information about a discovered clue
 */
export interface DiscoveredClue {
  /** Clue text content */
  text: string;
  /** Clue type: scenario clue, NPC clue, or secret */
  type: "scenario" | "npc" | "secret";
  /** Source name (scenario name or NPC name) */
  sourceName: string;
  /** Who discovered this clue */
  discoveredBy: string;
  /** When discovered (ISO format) */
  discoveredAt: string;
  /** Clue category (scenario clues only) */
  category?: "physical" | "witness" | "document" | "environment" | "knowledge" | "observation";
  /** Clue difficulty (scenario clues only) */
  difficulty?: "automatic" | "regular" | "hard" | "extreme";
  /** Discovery method */
  method?: string;
}

// Re-export GameState and GameStateManager from gameState.ts for backward compatibility
export type { GameState } from "./gameState.js";
export { GameStateManager, initialGameState } from "./gameState.js";

export type TimeConsumption = "instant" | "short" | "scene";

export interface DirectorDecision {
  shouldProgress: boolean;
  targetSnapshotId?: string;  // Specific scene snapshot ID to progress to
  estimatedShortActions?: number | null; // Estimated number of short actions executable in target scene
  increaseShortActionCapBy?: number | null; // When not progressing, increase current scene short action cap
  reasoning: string;          // Reason for progression
  timestamp: Date;            // Decision time
}

export interface ActionResult {
  timestamp: Date;
  gameTime: string;
  timeElapsedMinutes?: number; // Actual minutes consumed by the action
  location: string;
  character: string;
  result: string;
  diceRolls: string[];
  timeConsumption: TimeConsumption;  // Time consumption type of this action
  scenarioChanges?: string[]; // List of permanent changes made to the scenario
}

export interface AgentResult {
  agentId: AgentId;
  content: string;
  timestamp: Date;
  metadata?: any;
}
