/**
 * World Module Loader
 * Loads modules generated by the Dynamic World Agent (world builder)
 * Handles the runtime scene/module files used by the simulation engine.
 */

import fs from "fs";
import path from "path";
import type {
  CoCDatabase,
  CoCDatabaseAdapter,
} from "../../shared/agents/memory/database/index.js";
import {
  scopeIdByModule,
  stripModuleScope,
} from "../../shared/agents/memory/database/moduleScope.js";
import { getPrismaClient } from "../../shared/agents/memory/database/prismaClient.js";
import { resolveEmailId } from "../../shared/agents/memory/database/userContext.js";
import type {
  ModuleSetup,
  ScenarioOutline,
  TransportEdge,
} from "./types.js";
import type { DynamicNPCProfile } from "./types.js";
import type { DynamicScene } from "./types.js";
import type { JunctionNode, RoadNode } from "./topologyTypes.js";
import { decodeSceneItemsPayload, encodeSceneItemsPayload } from "./sceneItemContextPayload.js";

/**
 * Runtime-relevant module data loaded from world-builder files.
 */
export interface LoadedWorldModule {
  moduleName: string;
  moduleSetup: ModuleSetup | null;
  scenarios: ScenarioOutline[];
  scenes: Map<string, DynamicScene>; // sceneId -> scene
  transportEdges: TransportEdge[];
  junctions: Map<string, JunctionNode>;
  roads: Map<string, RoadNode>;
}

interface WorldModuleImportData {
  npcs: DynamicNPCProfile[];
}

export interface SavedWorldModule extends LoadedWorldModule {
  importStats: {
    npcsLoaded: number;
    scenariosLoaded: number;
    scenesLoaded: number;
  };
}

export class WorldModuleLoader {
  private emailId?: string;

  constructor(
    _db: CoCDatabase | CoCDatabaseAdapter,
    options?: { emailId?: string }
  ) {
    this.emailId = options?.emailId;
  }

  private getEmailId(): string | undefined {
    return resolveEmailId(this.emailId);
  }

  private scopeByModule(id: string, moduleId: string): string {
    return scopeIdByModule(id, moduleId);
  }

  private resolveModuleSetupPath(moduleDir: string): string | null {
    const preferred = path.join(moduleDir, "module_setup.json");
    if (fs.existsSync(preferred)) return preferred;
    return null;
  }

  /**
   * Check if module directory has changed since last load
   */
  private async checkForChanges(moduleDir: string): Promise<{
    hasChanges: boolean;
    timestamp: number;
  }> {
    const timestampFile = path.join(moduleDir, ".last_world_load_timestamp");
    const currentTime = Date.now();

    // Get all JSON file modification times
    const files = [
      "scenarios_outline.json",
      "module_setup.json",
      "transport_edges.json",
    ];

    let latestMtime = 0;
    for (const file of files) {
      const filePath = path.join(moduleDir, file);
      if (fs.existsSync(filePath)) {
        const stats = fs.statSync(filePath);
        latestMtime = Math.max(latestMtime, stats.mtime.getTime());
      }
    }

    // Check NPC and scenario directories
    const npcsDir = path.join(moduleDir, `${path.basename(moduleDir)}_npc`);
    const scenariosDir = path.join(
      moduleDir,
      `${path.basename(moduleDir)}_Scenarios`
    );

    for (const dir of [npcsDir, scenariosDir]) {
      if (fs.existsSync(dir)) {
        const dirFiles = fs.readdirSync(dir).filter((f) => f.endsWith(".json"));
        for (const file of dirFiles) {
          const filePath = path.join(dir, file);
          const stats = fs.statSync(filePath);
          latestMtime = Math.max(latestMtime, stats.mtime.getTime());
        }
      }
    }

    // Check if we have existing data in database
    const emailId = this.getEmailId();
    const prisma = getPrismaClient();

    const existing = await prisma.moduleBackground.findFirst({
      where: {
        title: path.basename(moduleDir),
        ...(emailId ? { emailId } : {}),
      },
      select: { moduleId: true },
    });

    if (!existing) {
      return { hasChanges: true, timestamp: currentTime };
    }

    // Read last load timestamp
    let lastLoadTime = 0;
    if (fs.existsSync(timestampFile)) {
      try {
        lastLoadTime = Number.parseInt(fs.readFileSync(timestampFile, "utf8"));
      } catch {
        return { hasChanges: true, timestamp: currentTime };
      }
    }

    const hasChanges = latestMtime > lastLoadTime;
    return { hasChanges, timestamp: currentTime };
  }

  /**
   * Update the last load timestamp
   */
  private updateLastLoadTimestamp(moduleDir: string, timestamp: number): void {
    const timestampFile = path.join(moduleDir, ".last_world_load_timestamp");
    fs.writeFileSync(timestampFile, timestamp.toString(), "utf8");
  }

  /**
   * Load a complete world module from directory
   */
  async loadWorldModule(
    moduleDir: string,
    forceReload = false
  ): Promise<LoadedWorldModule | null> {
    console.log(`\n=== Loading World Module from: ${moduleDir} ===`);

    if (!fs.existsSync(moduleDir)) {
      console.log(`Directory does not exist: ${moduleDir}`);
      return null;
    }

    const moduleName = path.basename(moduleDir);

    // Check for changes unless forced reload
    if (!forceReload) {
      const { hasChanges } = await this.checkForChanges(moduleDir);
      if (!hasChanges) {
        console.log(
          `No changes detected for module "${moduleName}". Skipping reload.`
        );
        // Could return existing data from database here
        return null;
      }
    }

    console.log(`Loading world module: ${moduleName}`);

    try {
      // 1. Load module digest
      console.log(`  [1/5] Loading module setup...`);
      const moduleSetupFile = this.resolveModuleSetupPath(moduleDir);
      const moduleSetup = moduleSetupFile
        ? this.loadJSON<ModuleSetup>(moduleSetupFile)
        : null;
      console.log(
        `    Module setup loaded: ${moduleSetup?.weatherPresets?.length ?? 0} weather preset(s)`
      );

      // 2. Load scenario outlines
      console.log(`  [2/5] Loading scenarios_outline.json...`);
      const scenariosFile = path.join(moduleDir, "scenarios_outline.json");
      const scenariosData = this.loadJSON<{ scenarios: ScenarioOutline[] }>(
        scenariosFile
      );
      console.log(`    Scenario outlines: ${scenariosData.scenarios.length}`);

      // 3. Load transport network (may not exist for old modules)
      let transportEdges: TransportEdge[] = [];
      const transportFile = path.join(moduleDir, "transport_edges.json");
      if (fs.existsSync(transportFile)) {
        console.log(`  [3/5] Loading transport_edges.json...`);
        const transportData = this.loadJSON<{
          transportEdges: TransportEdge[];
        }>(transportFile);
        transportEdges = transportData.transportEdges || [];
      } else {
        console.log(`  [3/5] transport_edges.json not found, using empty transport graph`);
      }

      // 4. Load scenes from individual scenario files
      console.log(`  [4/5] Loading scenes...`);
      const scenariosDir = path.join(moduleDir, `${moduleName}_Scenarios`);
      const scenes = this.loadDynamicScenes(scenariosDir);
      console.log(`    Scenes loaded: ${scenes.size}`);

      // 5. Load junctions and roads
      console.log(`  [5/5] Loading junctions and roads...`);
      const junctions = this.loadJunctions(scenariosDir);
      const roads = this.loadRoads(scenariosDir);
      console.log(`    Junctions loaded: ${junctions.size}`);
      console.log(`    Roads loaded: ${roads.size}`);

      const loadedModule: LoadedWorldModule = {
        moduleName,
        moduleSetup,
        scenarios: scenariosData.scenarios,
        scenes,
        transportEdges,
        junctions,
        roads,
      };

      console.log(`\nWorld module loaded successfully: ${moduleName}`);
      console.log(`   - Scenarios: ${loadedModule.scenarios.length}`);
      console.log(`   - Scenes: ${loadedModule.scenes.size}`);

      return loadedModule;
    } catch (error) {
      console.error(`Failed to load world module from ${moduleDir}:`, error);
      throw error;
    }
  }

  /**
   * Load and save world module to database
   */
  async loadAndSaveWorldModule(
    moduleDir: string,
    forceReload = false
  ): Promise<SavedWorldModule | null> {
    const module = await this.loadWorldModule(moduleDir, forceReload);

    if (!module) {
      return null;
    }

    console.log(`\nSaving world module to database: ${module.moduleName}`);

    try {
      const importData = this.loadWorldImportData(moduleDir, module.moduleName);

      // Save to database
      await this.saveToDatabase(module, importData);

      // Update timestamp
      const { timestamp } = await this.checkForChanges(moduleDir);
      this.updateLastLoadTimestamp(moduleDir, timestamp);

      console.log(`World module saved to database: ${module.moduleName}\n`);

      return {
        ...module,
        importStats: {
          npcsLoaded: importData.npcs.length,
          scenariosLoaded: module.scenarios.length,
          scenesLoaded: module.scenes.size,
        },
      };
    } catch (error) {
      console.error(`Failed to save world module to database:`, error);
      throw error;
    }
  }

  /**
   * Load JSON file with error handling
   */
  private loadJSON<T>(filePath: string): T {
    if (!fs.existsSync(filePath)) {
      throw new Error(`File not found: ${filePath}`);
    }

    try {
      const content = fs.readFileSync(filePath, "utf8");
      return JSON.parse(content) as T;
    } catch (error) {
      throw new Error(
        `Failed to parse JSON from ${filePath}: ${(error as Error).message}`
      );
    }
  }

  /**
   * Load scenes from individual DynamicScene JSON files (SCN_*.json).
   */
  private loadDynamicScenes(
    scenariosDir: string
  ): Map<string, DynamicScene> {
    const scenes = new Map<string, DynamicScene>();

    if (!fs.existsSync(scenariosDir)) {
      console.warn(`    Scenarios directory not found: ${scenariosDir}`);
      return scenes;
    }

    const files = fs
      .readdirSync(scenariosDir)
      .filter((f) => f.endsWith(".json") && !f.startsWith("JUNC_") && !f.startsWith("ROAD_"));

    for (const file of files) {
      try {
        const filePath = path.join(scenariosDir, file);
        const content = fs.readFileSync(filePath, "utf8");
        const data = JSON.parse(content);

        const { items, itemContexts } = decodeSceneItemsPayload(data.items);
        const scene: DynamicScene = {
          id: data.id,
          name: data.name,
          description: data.description || "",
          parentLocationId: data.parentLocationId || "",
          items,
          itemContexts,
          conditions: data.conditions || [],
          connections: data.connections || [],
          sceneImage: data.sceneImage,
        };
        scenes.set(scene.id, scene);
      } catch (error) {
        console.warn(`    Failed to load scenario file ${file}:`, error);
      }
    }

    return scenes;
  }

  /**
   * Load junction nodes from JUNC_*.json files.
   */
  private loadJunctions(scenariosDir: string): Map<string, JunctionNode> {
    const junctions = new Map<string, JunctionNode>();
    if (!fs.existsSync(scenariosDir)) return junctions;

    const files = fs.readdirSync(scenariosDir)
      .filter((f) => f.startsWith("JUNC_") && f.endsWith(".json"));

    for (const file of files) {
      try {
        const filePath = path.join(scenariosDir, file);
        const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
        const { items, itemContexts } = decodeSceneItemsPayload(data.items);
        const junction: JunctionNode = {
          id: data.id,
          name: data.name,
          description: data.description || "",
          parentLocationId: data.parentLocationId || "OUTDOOR",
          items,
          itemContexts,
          conditions: data.conditions || [],
          connectedSceneIds: data.connectedSceneIds || [],
        };
        junctions.set(junction.id, junction);
      } catch (error) {
        console.warn(`    Failed to load junction file ${file}:`, error);
      }
    }
    return junctions;
  }

  /**
   * Load road nodes from ROAD_*.json files.
   */
  private loadRoads(scenariosDir: string): Map<string, RoadNode> {
    const roads = new Map<string, RoadNode>();
    if (!fs.existsSync(scenariosDir)) return roads;

    const files = fs.readdirSync(scenariosDir)
      .filter((f) => f.startsWith("ROAD_") && f.endsWith(".json"));

    for (const file of files) {
      try {
        const filePath = path.join(scenariosDir, file);
        const data = JSON.parse(fs.readFileSync(filePath, "utf8"));

        const { items, itemContexts } = decodeSceneItemsPayload(data.items);
        const road: RoadNode = {
          id: data.id,
          name: data.name,
          description: data.description || "",
          parentLocationId: data.parentLocationId || "OUTDOOR",
          endpointA: data.endpointA,
          endpointB: data.endpointB,
          travelTimeMinutes: data.travelTimeMinutes ?? 10,
          alongConnections: (data.alongConnections || []).map((ac: any) => ({
            sceneId: ac.sceneId,
            position: ac.position,
          })),
          items,
          itemContexts,
          conditions: data.conditions || [],
        };
        roads.set(road.id, road);
      } catch (error) {
        console.warn(`    Failed to load road file ${file}:`, error);
      }
    }
    return roads;
  }

  /**
   * Load NPCs from individual NPC files
   */
  private loadNPCs(npcsDir: string): DynamicNPCProfile[] {
    const npcs: DynamicNPCProfile[] = [];

    if (!fs.existsSync(npcsDir)) {
      console.warn(`    NPCs directory not found: ${npcsDir}`);
      return npcs;
    }

    const files = fs.readdirSync(npcsDir).filter((f) => f.endsWith(".json"));

    for (const file of files) {
      try {
        const filePath = path.join(npcsDir, file);
        const content = fs.readFileSync(filePath, "utf8");
        const npc = JSON.parse(content) as DynamicNPCProfile;

        // Validate required NPC fields
        if (!npc.id || !npc.name) {
          console.warn(`    Invalid NPC in ${file}: missing id or name`);
          continue;
        }

        npcs.push(npc);
      } catch (error) {
        console.warn(`    Failed to load NPC file ${file}:`, error);
      }
    }

    return npcs;
  }

  /**
   * Load file-only module data used for database import, not runtime state.
   */
  private loadWorldImportData(
    moduleDir: string,
    moduleName: string
  ): WorldModuleImportData {
    console.log(`  [import] Loading NPCs...`);

    const npcsDir = path.join(moduleDir, `${moduleName}_npc`);
    const npcs = this.loadNPCs(npcsDir);
    console.log(`    NPCs loaded: ${npcs.length}`);

    return {
      npcs,
    };
  }

  /**
   * Save loaded world module to database
   */
  private async saveToDatabase(
    module: LoadedWorldModule,
    importData: WorldModuleImportData
  ): Promise<void> {
    // 1. Save module background
    console.log(`  [1/4] Saving module background...`);
    const moduleId = await this.saveModuleBackground(module, importData);

    // 2. Save NPCs
    console.log(`  [2/4] Saving ${importData.npcs.length} NPCs...`);
    await this.saveNPCs(importData.npcs, moduleId);

    // 3. Save scenarios
    console.log(`  [3/4] Saving ${module.scenarios.length} scenarios...`);
    await this.saveScenarios(module, moduleId);

    // 4. Save scenes
    console.log(
      `  [4/4] Saving ${module.scenes.size} scenes...`
    );
    await this.saveDynamicScenes(module, moduleId);

    console.log(`  All data saved to database`);
  }

  /**
   * Save module background to database
   */
  private async saveModuleBackground(
    module: LoadedWorldModule,
    importData: WorldModuleImportData
  ): Promise<string> {
    const prisma = getPrismaClient();
    const emailId = this.getEmailId();
    const ownerEmailId = emailId || "__system__";
    const normalizedName = module.moduleName.trim().toLowerCase();

    const moduleRow = await prisma.module.upsert({
      where: {
        uq_modules_owner_name_normalized: {
          ownerEmailId,
          moduleNameNormalized: normalizedName,
        },
      },
      update: {
        moduleName: module.moduleName,
        moduleNameNormalized: normalizedName,
        status: "active",
        updatedAt: new Date(),
      },
      create: {
        moduleName: module.moduleName,
        moduleNameNormalized: normalizedName,
        ownerEmailId,
        share: false,
        status: "active",
      },
      select: { moduleId: true, share: true },
    });

    if (emailId) {
      await prisma.modulePermission.upsert({
        where: {
          moduleId_emailId: { moduleId: moduleRow.moduleId, emailId },
        },
        update: {
          role: "owner",
          canPlay: true,
          canManage: true,
          grantedAt: new Date(),
        },
        create: {
          moduleId: moduleRow.moduleId,
          emailId,
          role: "owner",
          canPlay: true,
          canManage: true,
        },
      });
    }
    const moduleId = moduleRow.moduleId;

    // Derive background from runtime metadata only.
    const background =
      module.scenarios
        .slice(0, 3)
        .map((scenario) => `${scenario.name}: ${scenario.description}`)
        .join(" ") ||
      module.moduleName;

    // Generate story outline from scenarios
    const storyOutline = module.scenarios
      .map((s, i) => `${i + 1}. ${s.name}: ${s.description}`)
      .join("\n");

    // Get initial game time from module digest (scenes no longer carry gameTime)
    const initialGameTime: string | null = null;

    // Characters are no longer stored on scenes; initial NPC names come from module.npcs
    const initialScenarioNPCs: string[] = importData.npcs.map((npc) => npc.name);

    // Auto-generate tags
    const tags = [
      "auto-generated",
      "world-builder",
    ];

    await prisma.moduleBackground.upsert({
      where: { moduleId },
      update: {
        title: module.moduleName,
        background,
        storyOutline,
        moduleNotes: null,
        keeperGuidance: null,
        moduleLimitations: null,
        initialGameTime,
        initialScenarioNpcs: initialScenarioNPCs,
        introduction: null,
        tags,
        emailId: emailId || null,
        macroMapPath: null,
      },
      create: {
        moduleId,
        title: module.moduleName,
        background,
        storyOutline,
        moduleNotes: null,
        keeperGuidance: null,
        moduleLimitations: null,
        initialGameTime,
        initialScenarioNpcs: initialScenarioNPCs,
        introduction: null,
        tags,
        emailId: emailId || null,
        macroMapPath: null,
      },
    });

    return moduleId;
  }

  /**
   * Save NPCs to database
   */
  private async saveNPCs(
    npcs: DynamicNPCProfile[],
    moduleId: string
  ): Promise<void> {
    const prisma = getPrismaClient();
    const emailId = this.getEmailId();
    const scopedNpcIds = new Set(
      npcs.map((npc) => this.scopeByModule(npc.id, moduleId))
    );

    // Pass 1: ensure all NPC characters exist before writing dependent rows.
    for (const npc of npcs) {
      const npcId = this.scopeByModule(npc.id, moduleId);
      const rawNpcId = stripModuleScope(npc.id);
      const legacyEmailScopedNpcId = emailId ? `${emailId}::${rawNpcId}` : null;

      // Cleanup legacy email-scoped IDs so new state won't expose email prefixes.
      if (legacyEmailScopedNpcId && legacyEmailScopedNpcId !== npcId) {
        await prisma.npcRelationship.deleteMany({
          where: {
            OR: [
              { sourceId: legacyEmailScopedNpcId },
              { targetId: legacyEmailScopedNpcId },
            ],
            ...(emailId ? { emailId } : {}),
          },
        });
        await prisma.character.deleteMany({
          where: {
            characterId: legacyEmailScopedNpcId,
            isNpc: true,
            ...(emailId ? { emailId } : {}),
          },
        });
      }

      await prisma.character.upsert({
        where: { characterId: npcId },
        update: {
          name: npc.name,
          occupation: npc.occupation || null,
          age: npc.age || null,
          gender: npc.gender || null,
          appearance: npc.appearance || null,
          personality: npc.personality || null,
          background: npc.background || null,
          attributes: npc.attributes,
          status: npc.status,
          skills: npc.skills,
          inventory: npc.inventory as any,
          goals: npc.goals || [],
          secrets: npc.secrets || [],
          notes: npc.notes || null,
          currentLocation: null, // currentLocation removed - location tracked via actionLog
          instantiatedFrom: npc.instantiatedFrom || null,
          inheritsKnowledge: npc.inheritsKnowledge || [],
          emailId: emailId || null,
        },
        create: {
          characterId: npcId,
          name: npc.name,
          occupation: npc.occupation || null,
          age: npc.age || null,
          gender: npc.gender || null,
          appearance: npc.appearance || null,
          personality: npc.personality || null,
          background: npc.background || null,
          attributes: npc.attributes,
          status: npc.status,
          skills: npc.skills,
          inventory: npc.inventory as any,
          goals: npc.goals || [],
          secrets: npc.secrets || [],
          notes: npc.notes || null,
          isNpc: true,
          currentLocation: null, // currentLocation removed - location tracked via actionLog
          instantiatedFrom: npc.instantiatedFrom || null,
          inheritsKnowledge: npc.inheritsKnowledge || [],
          emailId: emailId || null,
        },
      });
    }

    // Collect relationship targets that are not in this NPC batch.
    const externalTargetIds = new Set<string>();
    for (const npc of npcs) {
      if (!npc.relationships || npc.relationships.length === 0) continue;
      for (const rel of npc.relationships) {
        const rawTargetId =
          typeof rel.targetId === "string" ? rel.targetId.trim() : "";
        if (!rawTargetId) continue;
        const scopedTargetId = this.scopeByModule(rawTargetId, moduleId);
        if (!scopedNpcIds.has(scopedTargetId)) {
          externalTargetIds.add(scopedTargetId);
        }
      }
    }

    const existingExternalTargetIds = new Set<string>();
    if (externalTargetIds.size > 0) {
      const existingTargets = await prisma.character.findMany({
        where: { characterId: { in: Array.from(externalTargetIds) } },
        select: { characterId: true },
      });
      for (const row of existingTargets) {
        existingExternalTargetIds.add(row.characterId);
      }
    }

    // Pass 3: save relationships (requires source and target characters to exist).
    let skippedRelationships = 0;
    for (const npc of npcs) {
      const npcId = this.scopeByModule(npc.id, moduleId);

      if (npc.relationships && npc.relationships.length > 0) {
        for (const rel of npc.relationships) {
          const rawTargetId =
            typeof rel.targetId === "string" ? rel.targetId.trim() : "";
          if (!rawTargetId) {
            skippedRelationships++;
            console.warn(
              `[WorldModuleLoader] Skip relationship with empty targetId: ${npc.name} -> ${rel.targetName || "unknown"}`
            );
            continue;
          }
          const targetId = this.scopeByModule(rawTargetId, moduleId);
          const targetExists =
            scopedNpcIds.has(targetId) ||
            existingExternalTargetIds.has(targetId);
          if (!targetExists) {
            skippedRelationships++;
            console.warn(
              `[WorldModuleLoader] Skip relationship, target character not found: ${npc.name} -> ${rel.targetName} (${targetId})`
            );
            continue;
          }

          const relId = this.scopeByModule(
            `${stripModuleScope(npc.id)}_${rel.targetName}`,
            moduleId
          );

          await prisma.npcRelationship.upsert({
            where: { id: relId },
            update: {
              sourceId: npcId,
              targetId,
              targetName: rel.targetName,
              relationshipType: rel.relationshipType,
              attitude: rel.attitude,
              description: rel.description || null,
              history: rel.history || null,
              emailId: emailId || null,
            },
            create: {
              id: relId,
              sourceId: npcId,
              targetId,
              targetName: rel.targetName,
              relationshipType: rel.relationshipType,
              attitude: rel.attitude,
              description: rel.description || null,
              history: rel.history || null,
              emailId: emailId || null,
            },
          });
        }
      }
    }

    if (skippedRelationships > 0) {
      console.warn(
        `[WorldModuleLoader] Skipped ${skippedRelationships} unresolved NPC relationships`
      );
    }
  }

  /**
   * Save scenarios to database
   */
  private async saveScenarios(
    module: LoadedWorldModule,
    moduleId: string
  ): Promise<void> {
    const prisma = getPrismaClient();
    const now = new Date().toISOString();

    for (const scenario of module.scenarios) {
      const scopedScenarioId = this.scopeByModule(scenario.id, moduleId);
      const metadata = {
        createdAt: now,
        updatedAt: now,
        source: "world_builder",
        author: "world_builder",
        gameSystem: "CoC 7e",
      };

      await prisma.scenario.upsert({
        where: {
          moduleId_scenarioId: {
            moduleId,
            scenarioId: scopedScenarioId,
          },
        },
        update: {
          moduleId,
          name: scenario.name,
          description: scenario.description,
          residents: (scenario.residents || []) as any,
          subSceneCount: scenario.subSceneCount ?? null,
          metadata,
          sourcePlaceId: scenario.sourcePlaceId || null,
          mapImagePath: null,
        },
        create: {
          scenarioId: scopedScenarioId,
          moduleId,
          name: scenario.name,
          description: scenario.description,
          residents: (scenario.residents || []) as any,
          subSceneCount: scenario.subSceneCount ?? null,
          metadata,
          sourcePlaceId: scenario.sourcePlaceId || null,
          mapImagePath: null,
        },
      });
    }
  }

  /**
   * Save DynamicScene objects to database.
   * Characters are no longer saved per-scene — they live on NPCs.
   */
  private async saveDynamicScenes(
    module: LoadedWorldModule,
    moduleId: string
  ): Promise<void> {
    const prisma = getPrismaClient();

    for (const [sceneId, scene] of module.scenes.entries()) {
      const scopedSceneId = this.scopeByModule(sceneId, moduleId);

      // Check if scene row already exists for this module (compound PK)
      const existing = await prisma.scene.findFirst({
        where: { moduleId, sceneId: scopedSceneId },
        select: { sceneId: true },
      });

      if (existing) {
        continue; // Skip existing rows
      }

      // Find corresponding scenario outline
      const scenario = module.scenarios.find(
        (s) => s.id === scene.id || s.name === scene.name
      );
      const scenarioId = scenario?.id || sceneId;
      const scopedScenarioId = this.scopeByModule(scenarioId, moduleId);

      const sceneImagePath = scene.sceneImage?.path || null;

      // Insert scene row
      await prisma.scene.create({
        data: {
          sceneId: scopedSceneId,
          scenarioId: scopedScenarioId,
          moduleId,
          name: scene.name,
          description: scene.description,
          parentLocationId: scene.parentLocationId || null,
          connections: (scene.connections || []) as any,
          items: encodeSceneItemsPayload(scene) as any,
          sceneImagePath,
        },
      });

      // Insert conditions
      if (scene.conditions && scene.conditions.length > 0) {
        for (const condition of scene.conditions) {
          const conditionId = `${scopedSceneId}-cond-${Math.random().toString(36).slice(2, 10)}`;

          try {
            await prisma.scenarioCondition.create({
              data: {
                conditionId,
                sceneId: scopedSceneId,
                moduleId,
                description: condition.description,
                mechanicalEffect: condition.mechanicalEffect ?? undefined,
              },
            });
          } catch (error: any) {
            // P2002: Unique constraint violation - ignore duplicates
            if (error?.code !== "P2002") {
              throw error;
            }
          }
        }
      }
    }
  }
}
