/**
 * World Builder API Controller
 * Handles world generation requests via SSE
 */

import type { Request, Response } from "express";
import { WorldBuilderService } from "../../../src/dynamicworldagent/world_builder/worldBuilderService.js";
import { DatabaseManager } from "../core/DatabaseManager.js";

/**
 * Generate world content for a module
 * POST /api/module/generate-world
 * Uses SSE for progress reporting
 */
export async function generateWorld(req: Request, res: Response): Promise<void> {
  // Enable SSE for progress reporting
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no"); // Disable nginx buffering

  try {
    const { settingType, creativePrompt } = req.body;

    if (!creativePrompt || typeof creativePrompt !== "string") {
      res.write(
        `data: ${JSON.stringify({
          stage: "error",
          progress: 0,
          message: "creativePrompt is required (e.g., 'A 1920s fishing village where locals worship Dagon')",
        })}\n\n`
      );
      res.end();
      return;
    }

    // Validate settingType if provided
    const validSettingTypes = ["small_town", "city", "academic", "isolated", "single_structure", "route"];
    const selectedSettingType = settingType && validSettingTypes.includes(settingType)
      ? settingType
      : "small_town";

    console.log(`\n🌍 [World Builder API] Request received`);
    console.log(`   Setting Type: ${selectedSettingType}`);
    console.log(`   Creative Prompt: ${creativePrompt.substring(0, 100)}${creativePrompt.length > 100 ? '...' : ''}`);

    // Get database instance
    const db = DatabaseManager.getInstance().getDatabase();

    // Run world generation with progress callback
    // Module name will be generated by the AI
    const service = new WorldBuilderService();

    const result = await service.generateWorld(
      db,
      selectedSettingType as any,
      creativePrompt.trim(),
      (stage, progress, message) => {
        res.write(
          `data: ${JSON.stringify({ stage, progress, message })}\n\n`
        );
      }
    );

    // Send final result with summary (including generated module name)
    res.write(
      `data: ${JSON.stringify({
        stage: "complete",
        progress: 100,
        result: {
          moduleName: result.macroScene.moduleName,
          locationName: result.macroScene.locationName,
          npcCount: result.npcs.length,
          truthEventCount: result.truthTimeline.length,
          knowledgeHolderCount: result.knowledgeMatrix.length,
          files: {
            truthTimeline: result.generatedFiles.truthTimelineFile,
            knowledgeMatrix: result.generatedFiles.knowledgeMatrixFile,
            macroScene: result.generatedFiles.macroSceneFile,
            npcsDir: result.generatedFiles.npcsDir,
          },
        },
      })}\n\n`
    );
    res.end();

    console.log(`✅ [World Builder API] Generation complete for ${result.macroScene.moduleName}`);
  } catch (error) {
    console.error("❌ [World Builder API] Error:", error);

    res.write(
      `data: ${JSON.stringify({
        stage: "error",
        progress: 0,
        message: `Generation failed: ${(error as Error).message}`,
      })}\n\n`
    );
    res.end();
  }
}

/**
 * Generate scene-only content for a module
 * POST /api/module/generate-scene
 * Uses SSE for progress reporting
 */
export async function generateScene(req: Request, res: Response): Promise<void> {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no");

  try {
    const { settingType, creativePrompt } = req.body;

    if (!creativePrompt || typeof creativePrompt !== "string") {
      res.write(
        `data: ${JSON.stringify({
          stage: "error",
          progress: 0,
          message: "creativePrompt is required (e.g., 'A 1920s fishing village where locals worship Dagon')",
        })}\n\n`
      );
      res.end();
      return;
    }

    const validSettingTypes = ["small_town", "city", "academic", "isolated", "single_structure", "route"];
    const selectedSettingType = settingType && validSettingTypes.includes(settingType)
      ? settingType
      : "small_town";

    console.log(`\n🌍 [World Builder API] Scene request received`);
    console.log(`   Setting Type: ${selectedSettingType}`);
    console.log(`   Creative Prompt: ${creativePrompt.substring(0, 100)}${creativePrompt.length > 100 ? '...' : ''}`);

    const service = new WorldBuilderService();

    const result = await service.generateScene(
      selectedSettingType as any,
      creativePrompt.trim(),
      (stage, progress, message) => {
        res.write(
          `data: ${JSON.stringify({ stage, progress, message })}\n\n`
        );
      }
    );

    res.write(
      `data: ${JSON.stringify({
        stage: "complete",
        progress: 100,
        result: {
          moduleName: result.macroScene.moduleName,
          locationName: result.macroScene.locationName,
          truthEventCount: result.truthTimeline.length,
          knowledgeHolderCount: result.knowledgeMatrix.length,
          files: {
            truthTimeline: result.generatedFiles.truthTimelineFile,
            knowledgeMatrix: result.generatedFiles.knowledgeMatrixFile,
            macroScene: result.generatedFiles.macroSceneFile,
            npcsDir: result.generatedFiles.npcsDir,
          },
        },
      })}\n\n`
    );
    res.end();

    console.log(`✅ [World Builder API] Scene generation complete for ${result.macroScene.moduleName}`);
  } catch (error) {
    console.error("❌ [World Builder API] Scene generation error:", error);

    res.write(
      `data: ${JSON.stringify({
        stage: "error",
        progress: 0,
        message: `Generation failed: ${(error as Error).message}`,
      })}\n\n`
    );
    res.end();
  }
}

/**
 * Generate NPCs for an existing module
 * POST /api/module/generate-npcs
 * Uses SSE for progress reporting
 */
export async function generateNpcs(req: Request, res: Response): Promise<void> {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no");

  try {
    const { moduleName } = req.body;

    if (!moduleName || typeof moduleName !== "string") {
      res.write(
        `data: ${JSON.stringify({
          stage: "error",
          progress: 0,
          message: "moduleName is required",
        })}\n\n`
      );
      res.end();
      return;
    }

    console.log(`\n👥 [World Builder API] NPC request received`);
    console.log(`   Module: ${moduleName}`);

    const service = new WorldBuilderService();

    const result = await service.generateNpcsForModule(
      moduleName.trim(),
      (stage, progress, message) => {
        res.write(
          `data: ${JSON.stringify({ stage, progress, message })}\n\n`
        );
      }
    );

    res.write(
      `data: ${JSON.stringify({
        stage: "complete",
        progress: 100,
        result: {
          moduleName: result.macroScene.moduleName,
          npcCount: result.npcs.length,
          files: {
            npcsDir: result.generatedFiles.npcsDir,
          },
        },
      })}\n\n`
    );
    res.end();

    console.log(`✅ [World Builder API] NPC generation complete for ${result.macroScene.moduleName}`);
  } catch (error) {
    console.error("❌ [World Builder API] NPC generation error:", error);

    res.write(
      `data: ${JSON.stringify({
        stage: "error",
        progress: 0,
        message: `Generation failed: ${(error as Error).message}`,
      })}\n\n`
    );
    res.end();
  }
}
