/**
 * World Module Loader
 * Loads modules generated by the Dynamic World Agent (world builder)
 * Handles the complete world-first module structure with truth timeline, knowledge matrix, etc.
 */

import fs from "fs";
import path from "path";
import type { CoCDatabase } from "../../coc_multiagents_system/agents/memory/database/schema.js";
import type {
  MacroSceneStructure,
  TruthEvent,
  KnowledgeHolder,
  RedHerring,
  MythosEvent,
  EndStateDefinition,
  ScenarioOutline,
  ModuleDigest,
} from "./types.js";
import type { DynamicNPCProfile } from "./types.js";
import type { DynamicScenarioSnapshot } from "./types.js";

/**
 * Complete world module data loaded from all JSON files
 */
export interface LoadedWorldModule {
  moduleName: string;
  moduleDigest: ModuleDigest & { title: string };
  macroScene: MacroSceneStructure;
  mythosEvents: MythosEvent[];
  endState: EndStateDefinition;
  truthTimeline: TruthEvent[];
  knowledgeMatrix: KnowledgeHolder[];
  redHerrings: RedHerring[];
  scenarios: ScenarioOutline[];
  scenarioSnapshots: Map<string, DynamicScenarioSnapshot>; // scenarioId -> snapshot
  npcs: DynamicNPCProfile[];
  files: {
    truthTimelineFile: string;
    knowledgeMatrixFile: string;
    macroSceneFile: string;
    scenariosFile: string;
    moduleDigestFile: string;
    scenariosDir: string;
    npcsDir: string;
  };
}

/**
 * Scenario file payload (array format with single entry)
 */
interface ScenarioFilePayload {
  name: string;
  description: string;
  evidence?: string[];
  clues?: any[];
  snapshot: DynamicScenarioSnapshot;
  tags?: string[];
  connections?: any[];
  npcAssignments?: any[];
}

export class WorldModuleLoader {
  private db: CoCDatabase;

  constructor(db: CoCDatabase) {
    this.db = db;
  }

  /**
   * Check if module directory has changed since last load
   */
  private checkForChanges(moduleDir: string): { hasChanges: boolean; timestamp: number } {
    const timestampFile = path.join(moduleDir, ".last_world_load_timestamp");
    const currentTime = Date.now();

    // Get all JSON file modification times
    const files = [
      "truth_timeline.json",
      "knowledge_matrix.json",
      "macro_scene.json",
      "scenarios_outline.json",
      "module_digest.json",
    ];

    let latestMtime = 0;
    for (const file of files) {
      const filePath = path.join(moduleDir, file);
      if (fs.existsSync(filePath)) {
        const stats = fs.statSync(filePath);
        latestMtime = Math.max(latestMtime, stats.mtime.getTime());
      }
    }

    // Check NPC and scenario directories
    const npcsDir = path.join(moduleDir, `${path.basename(moduleDir)}_npc`);
    const scenariosDir = path.join(moduleDir, `${path.basename(moduleDir)}_Scenarios`);

    for (const dir of [npcsDir, scenariosDir]) {
      if (fs.existsSync(dir)) {
        const dirFiles = fs.readdirSync(dir).filter((f) => f.endsWith(".json"));
        for (const file of dirFiles) {
          const filePath = path.join(dir, file);
          const stats = fs.statSync(filePath);
          latestMtime = Math.max(latestMtime, stats.mtime.getTime());
        }
      }
    }

    // Check if we have existing data in database
    const existing = this.db.getDatabase().prepare(
      `SELECT module_id FROM module_backgrounds WHERE title = ?`
    ).get(path.basename(moduleDir));

    if (!existing) {
      return { hasChanges: true, timestamp: currentTime };
    }

    // Read last load timestamp
    let lastLoadTime = 0;
    if (fs.existsSync(timestampFile)) {
      try {
        lastLoadTime = parseInt(fs.readFileSync(timestampFile, "utf8"));
      } catch {
        return { hasChanges: true, timestamp: currentTime };
      }
    }

    const hasChanges = latestMtime > lastLoadTime;
    return { hasChanges, timestamp: currentTime };
  }

  /**
   * Update the last load timestamp
   */
  private updateLastLoadTimestamp(moduleDir: string, timestamp: number): void {
    const timestampFile = path.join(moduleDir, ".last_world_load_timestamp");
    fs.writeFileSync(timestampFile, timestamp.toString(), "utf8");
  }

  /**
   * Load a complete world module from directory
   */
  async loadWorldModule(
    moduleDir: string,
    forceReload = false
  ): Promise<LoadedWorldModule | null> {
    console.log(`\n=== Loading World Module from: ${moduleDir} ===`);

    if (!fs.existsSync(moduleDir)) {
      console.log(`Directory does not exist: ${moduleDir}`);
      return null;
    }

    const moduleName = path.basename(moduleDir);

    // Check for changes unless forced reload
    if (!forceReload) {
      const { hasChanges } = this.checkForChanges(moduleDir);
      if (!hasChanges) {
        console.log(`No changes detected for module "${moduleName}". Skipping reload.`);
        // Could return existing data from database here
        return null;
      }
    }

    console.log(`📦 Loading world module: ${moduleName}`);

    try {
      // 1. Load module digest
      console.log(`  [1/7] Loading module_digest.json...`);
      const moduleDigestFile = path.join(moduleDir, "module_digest.json");
      const moduleDigest = this.loadJSON<ModuleDigest & { title: string }>(moduleDigestFile);
      console.log(`    ✓ Module digest loaded: ${moduleDigest.title}`);

      // 2. Load macro scene (includes mythos events and end state)
      console.log(`  [2/7] Loading macro_scene.json...`);
      const macroSceneFile = path.join(moduleDir, "macro_scene.json");
      const macroSceneData = this.loadJSON<{
        macroScene: MacroSceneStructure;
        mythosEvents: MythosEvent[];
        endState: EndStateDefinition;
      }>(macroSceneFile);
      console.log(`    ✓ Macro scene loaded: ${macroSceneData.macroScene.locationName}`);
      console.log(`    ✓ Mythos events: ${macroSceneData.mythosEvents.length}`);

      // 3. Load truth timeline
      console.log(`  [3/7] Loading truth_timeline.json...`);
      const truthTimelineFile = path.join(moduleDir, "truth_timeline.json");
      const truthTimelineData = this.loadJSON<{ truthTimeline: TruthEvent[] }>(truthTimelineFile);
      console.log(`    ✓ Truth events: ${truthTimelineData.truthTimeline.length}`);

      // 4. Load knowledge matrix and red herrings
      console.log(`  [4/7] Loading knowledge_matrix.json...`);
      const knowledgeMatrixFile = path.join(moduleDir, "knowledge_matrix.json");
      const knowledgeMatrixData = this.loadJSON<{
        knowledgeMatrix: KnowledgeHolder[];
        redHerrings: RedHerring[];
      }>(knowledgeMatrixFile);
      console.log(`    ✓ Knowledge holders: ${knowledgeMatrixData.knowledgeMatrix.length}`);
      console.log(`    ✓ Red herrings: ${knowledgeMatrixData.redHerrings.length}`);

      // 5. Load scenario outlines
      console.log(`  [5/7] Loading scenarios_outline.json...`);
      const scenariosFile = path.join(moduleDir, "scenarios_outline.json");
      const scenariosData = this.loadJSON<{ scenarios: ScenarioOutline[] }>(scenariosFile);
      console.log(`    ✓ Scenario outlines: ${scenariosData.scenarios.length}`);

      // 6. Load scenario snapshots from individual files
      console.log(`  [6/7] Loading scenario snapshots...`);
      const scenariosDir = path.join(moduleDir, `${moduleName}_Scenarios`);
      const scenarioSnapshots = this.loadDynamicScenarioSnapshots(scenariosDir);
      console.log(`    ✓ Scenario snapshots loaded: ${scenarioSnapshots.size}`);

      // 7. Load NPCs from individual files
      console.log(`  [7/7] Loading NPCs...`);
      const npcsDir = path.join(moduleDir, `${moduleName}_npc`);
      const npcs = this.loadNPCs(npcsDir);
      console.log(`    ✓ NPCs loaded: ${npcs.length}`);

      const loadedModule: LoadedWorldModule = {
        moduleName,
        moduleDigest,
        macroScene: macroSceneData.macroScene,
        mythosEvents: macroSceneData.mythosEvents,
        endState: macroSceneData.endState,
        truthTimeline: truthTimelineData.truthTimeline,
        knowledgeMatrix: knowledgeMatrixData.knowledgeMatrix,
        redHerrings: knowledgeMatrixData.redHerrings,
        scenarios: scenariosData.scenarios,
        scenarioSnapshots,
        npcs,
        files: {
          truthTimelineFile,
          knowledgeMatrixFile,
          macroSceneFile,
          scenariosFile,
          moduleDigestFile,
          scenariosDir,
          npcsDir,
        },
      };

      console.log(`\n✅ World module loaded successfully: ${moduleName}`);
      console.log(`   - Truth events: ${loadedModule.truthTimeline.length}`);
      console.log(`   - Knowledge holders: ${loadedModule.knowledgeMatrix.length}`);
      console.log(`   - Red herrings: ${loadedModule.redHerrings.length}`);
      console.log(`   - Scenarios: ${loadedModule.scenarios.length}`);
      console.log(`   - NPCs: ${loadedModule.npcs.length}`);

      return loadedModule;
    } catch (error) {
      console.error(`✗ Failed to load world module from ${moduleDir}:`, error);
      throw error;
    }
  }

  /**
   * Load and save world module to database
   */
  async loadAndSaveWorldModule(
    moduleDir: string,
    forceReload = false
  ): Promise<LoadedWorldModule | null> {
    const module = await this.loadWorldModule(moduleDir, forceReload);

    if (!module) {
      return null;
    }

    console.log(`\n💾 Saving world module to database: ${module.moduleName}`);

    try {
      // Save to database
      this.saveToDatabase(module);

      // Update timestamp
      const { timestamp } = this.checkForChanges(moduleDir);
      this.updateLastLoadTimestamp(moduleDir, timestamp);

      console.log(`✅ World module saved to database: ${module.moduleName}\n`);

      return module;
    } catch (error) {
      console.error(`✗ Failed to save world module to database:`, error);
      throw error;
    }
  }

  /**
   * Load all world modules from Mods directory
   */
  async loadAllWorldModules(forceReload = false): Promise<LoadedWorldModule[]> {
    const modsDir = path.join(process.cwd(), "data", "Mods");

    if (!fs.existsSync(modsDir)) {
      console.log(`Mods directory does not exist: ${modsDir}`);
      return [];
    }

    const moduleDirs = fs.readdirSync(modsDir).filter((dir) => {
      const fullPath = path.join(modsDir, dir);
      return fs.statSync(fullPath).isDirectory();
    });

    console.log(`\n=== Loading ${moduleDirs.length} world modules from ${modsDir} ===\n`);

    const loadedModules: LoadedWorldModule[] = [];

    for (let i = 0; i < moduleDirs.length; i++) {
      const dir = moduleDirs[i];
      const moduleDir = path.join(modsDir, dir);

      console.log(`[${i + 1}/${moduleDirs.length}] Loading module: ${dir}`);

      try {
        const module = await this.loadAndSaveWorldModule(moduleDir, forceReload);
        if (module) {
          loadedModules.push(module);
        }
      } catch (error) {
        console.error(`  ✗ Failed to load module ${dir}:`, error);
      }
    }

    console.log(`\n=== Successfully loaded ${loadedModules.length}/${moduleDirs.length} world modules ===\n`);

    return loadedModules;
  }

  /**
   * Load JSON file with error handling
   */
  private loadJSON<T>(filePath: string): T {
    if (!fs.existsSync(filePath)) {
      throw new Error(`File not found: ${filePath}`);
    }

    try {
      const content = fs.readFileSync(filePath, "utf8");
      return JSON.parse(content) as T;
    } catch (error) {
      throw new Error(`Failed to parse JSON from ${filePath}: ${(error as Error).message}`);
    }
  }

  /**
   * Load scenario snapshots from individual scenario files
   */
  private loadDynamicScenarioSnapshots(scenariosDir: string): Map<string, DynamicScenarioSnapshot> {
    const snapshots = new Map<string, DynamicScenarioSnapshot>();

    if (!fs.existsSync(scenariosDir)) {
      console.warn(`    ⚠️  Scenarios directory not found: ${scenariosDir}`);
      return snapshots;
    }

    const files = fs.readdirSync(scenariosDir).filter((f) => f.endsWith(".json"));

    for (const file of files) {
      try {
        const filePath = path.join(scenariosDir, file);
        const content = fs.readFileSync(filePath, "utf8");
        const data = JSON.parse(content);

        // Handle array format (single entry per file)
        const scenarios: ScenarioFilePayload[] = Array.isArray(data) ? data : [data];

        for (const scenario of scenarios) {
          if (scenario.snapshot) {
            const snapshot = scenario.snapshot;
            snapshots.set(snapshot.id, snapshot);
          }
        }
      } catch (error) {
        console.warn(`    ⚠️  Failed to load scenario file ${file}:`, error);
      }
    }

    return snapshots;
  }

  /**
   * Load NPCs from individual NPC files
   */
  private loadNPCs(npcsDir: string): DynamicNPCProfile[] {
    const npcs: DynamicNPCProfile[] = [];

    if (!fs.existsSync(npcsDir)) {
      console.warn(`    ⚠️  NPCs directory not found: ${npcsDir}`);
      return npcs;
    }

    const files = fs.readdirSync(npcsDir).filter((f) => f.endsWith(".json"));

    for (const file of files) {
      try {
        const filePath = path.join(npcsDir, file);
        const content = fs.readFileSync(filePath, "utf8");
        const npc = JSON.parse(content) as DynamicNPCProfile;

        // Validate required NPC fields
        if (!npc.id || !npc.name) {
          console.warn(`    ⚠️  Invalid NPC in ${file}: missing id or name`);
          continue;
        }

        npcs.push(npc);
      } catch (error) {
        console.warn(`    ⚠️  Failed to load NPC file ${file}:`, error);
      }
    }

    return npcs;
  }

  /**
   * Save loaded world module to database
   */
  private saveToDatabase(module: LoadedWorldModule): void {
    const database = this.db.getDatabase();

    // 1. Save module background
    console.log(`  [1/4] Saving module background...`);
    this.saveModuleBackground(module);

    // 2. Save NPCs
    console.log(`  [2/4] Saving ${module.npcs.length} NPCs...`);
    this.saveNPCs(module.npcs);

    // 3. Save scenarios
    console.log(`  [3/4] Saving ${module.scenarios.length} scenarios...`);
    this.saveScenarios(module);

    // 4. Save scenario snapshots
    console.log(`  [4/4] Saving ${module.scenarioSnapshots.size} scenario snapshots...`);
    this.saveDynamicScenarioSnapshots(module);

    console.log(`  ✓ All data saved to database`);
  }

  /**
   * Save module background to database
   */
  private saveModuleBackground(module: LoadedWorldModule): void {
    const database = this.db.getDatabase();
    const moduleId = `module-${module.moduleName.toLowerCase().replace(/\s+/g, "-")}`;

    // Generate background from macro scene
    const background = `${module.macroScene.locationName} - ${module.macroScene.settingType || "setting"}. ${module.macroScene.economicCore}`;

    // Generate story outline from scenarios
    const storyOutline = module.scenarios
      .map((s, i) => `${i + 1}. ${s.name}: ${s.description}`)
      .join("\n");

    // Get initial game time from first scenario snapshot (usually starting scene)
    let initialGameTime = null;
    const firstSnapshot = module.scenarioSnapshots.values().next().value;
    if (firstSnapshot?.gameTime) {
      initialGameTime = firstSnapshot.gameTime;
    }

    // Get initial scenario NPCs from starting scene
    const initialScenarioNPCs: string[] = [];
    if (firstSnapshot?.characters) {
      initialScenarioNPCs.push(...firstSnapshot.characters.map((c: any) => c.name));
    }

    // Auto-generate tags
    const tags = [
      "auto-generated",
      "world-builder",
      module.macroScene.settingType || "unknown",
      ...module.mythosEvents.map((e) => e.mythosEntityInvolved.toLowerCase()),
    ];

    // Check column availability
    const hasInitialGameTime = this.db.hasColumn("module_backgrounds", "initial_game_time");
    const hasIntroduction = this.db.hasColumn("module_backgrounds", "introduction");
    const hasInitialScenarioNPCs = this.db.hasColumn("module_backgrounds", "initial_scenario_npcs");

    if (hasInitialGameTime && hasIntroduction && hasInitialScenarioNPCs) {
      const stmt = database.prepare(`
        INSERT OR REPLACE INTO module_backgrounds (
          module_id, title, background, story_outline, module_notes,
          keeper_guidance, module_limitations, initial_game_time,
          initial_scenario_npcs, introduction, tags
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);

      stmt.run(
        moduleId,
        module.moduleName,
        background,
        storyOutline,
        module.moduleDigest.moduleNotes,
        module.moduleDigest.keeperGuidance,
        module.moduleDigest.moduleLimitations,
        initialGameTime,
        JSON.stringify(initialScenarioNPCs),
        module.moduleDigest.introduction,
        JSON.stringify(tags)
      );
    } else if (hasInitialGameTime && hasInitialScenarioNPCs) {
      const stmt = database.prepare(`
        INSERT OR REPLACE INTO module_backgrounds (
          module_id, title, background, story_outline, module_notes,
          keeper_guidance, module_limitations, initial_game_time,
          initial_scenario_npcs, tags
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);

      stmt.run(
        moduleId,
        module.moduleName,
        background,
        storyOutline,
        module.moduleDigest.moduleNotes,
        module.moduleDigest.keeperGuidance,
        module.moduleDigest.moduleLimitations,
        initialGameTime,
        JSON.stringify(initialScenarioNPCs),
        JSON.stringify(tags)
      );
    } else if (hasInitialGameTime) {
      const stmt = database.prepare(`
        INSERT OR REPLACE INTO module_backgrounds (
          module_id, title, background, story_outline, module_notes,
          keeper_guidance, module_limitations, initial_game_time, tags
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);

      stmt.run(
        moduleId,
        module.moduleName,
        background,
        storyOutline,
        module.moduleDigest.moduleNotes,
        module.moduleDigest.keeperGuidance,
        module.moduleDigest.moduleLimitations,
        initialGameTime,
        JSON.stringify(tags)
      );
    } else {
      const stmt = database.prepare(`
        INSERT OR REPLACE INTO module_backgrounds (
          module_id, title, background, story_outline, module_notes,
          keeper_guidance, module_limitations, tags
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
      `);

      stmt.run(
        moduleId,
        module.moduleName,
        background,
        storyOutline,
        module.moduleDigest.moduleNotes,
        module.moduleDigest.keeperGuidance,
        module.moduleDigest.moduleLimitations,
        JSON.stringify(tags)
      );
    }

    // Save extended world data (truth timeline, knowledge matrix, etc.) if columns exist
    if (this.db.hasColumn("module_backgrounds", "truth_timeline")) {
      const updateStmt = database.prepare(`
        UPDATE module_backgrounds
        SET truth_timeline = ?,
            knowledge_matrix = ?,
            red_herrings = ?,
            historical_mythos = ?,
            end_state_definition = ?,
            macro_scene_structure = ?,
            global_trigger = ?
        WHERE module_id = ?
      `);

      updateStmt.run(
        JSON.stringify(module.truthTimeline),
        JSON.stringify(module.knowledgeMatrix),
        JSON.stringify(module.redHerrings),
        JSON.stringify(module.mythosEvents),
        JSON.stringify(module.endState),
        JSON.stringify(module.macroScene),
        module.moduleDigest.globalTrigger ? JSON.stringify(module.moduleDigest.globalTrigger) : null,
        moduleId
      );
    }
  }

  /**
   * Save NPCs to database
   */
  private saveNPCs(npcs: DynamicNPCProfile[]): void {
    const database = this.db.getDatabase();

    for (const npc of npcs) {
      // Check if NPC already exists
      const existing = database
        .prepare(`SELECT character_id FROM characters WHERE character_id = ?`)
        .get(npc.id);

      if (existing) {
        // Update existing NPC
        const updateStmt = database.prepare(`
          UPDATE characters
          SET name = ?, occupation = ?, age = ?, gender = ?, appearance = ?,
              personality = ?, background = ?, attributes = ?, status = ?,
              skills = ?, inventory = ?, goals = ?, secrets = ?, notes = ?,
              current_location = ?, instantiated_from = ?, inherits_knowledge = ?
          WHERE character_id = ?
        `);

        updateStmt.run(
          npc.name,
          npc.occupation || null,
          npc.age || null,
          npc.gender || null,
          npc.appearance || null,
          npc.personality || null,
          npc.background || null,
          JSON.stringify(npc.attributes),
          JSON.stringify(npc.status),
          JSON.stringify(npc.skills),
          JSON.stringify(npc.inventory),
          JSON.stringify(npc.goals || []),
          JSON.stringify(npc.secrets || []),
          npc.notes || null,
          null, // currentLocation removed - location tracked via actionLog
          npc.instantiatedFrom || null,
          JSON.stringify(npc.inheritsKnowledge || []),
          npc.id
        );
      } else {
        // Insert new NPC
        const insertStmt = database.prepare(`
          INSERT INTO characters (
            character_id, name, occupation, age, gender, appearance, personality,
            background, attributes, status, skills, inventory, goals, secrets,
            notes, is_npc, current_location, instantiated_from, inherits_knowledge
          ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?)
        `);

        insertStmt.run(
          npc.id,
          npc.name,
          npc.occupation || null,
          npc.age || null,
          npc.gender || null,
          npc.appearance || null,
          npc.personality || null,
          npc.background || null,
          JSON.stringify(npc.attributes),
          JSON.stringify(npc.status),
          JSON.stringify(npc.skills),
          JSON.stringify(npc.inventory),
          JSON.stringify(npc.goals || []),
          JSON.stringify(npc.secrets || []),
          npc.notes || null,
          null, // currentLocation removed - location tracked via actionLog
          npc.instantiatedFrom || null,
          JSON.stringify(npc.inheritsKnowledge || [])
        );
      }

      // Save NPC clues
      if (npc.clues && npc.clues.length > 0) {
        for (const clue of npc.clues) {
          const clueStmt = database.prepare(`
            INSERT OR REPLACE INTO npc_clues (
              id, npc_id, clue_text, category, difficulty, revealed, related_to
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
          `);

          clueStmt.run(
            clue.id,
            npc.id,
            clue.clueText,
            clue.category || null,
            clue.difficulty || null,
            clue.revealed ? 1 : 0,
            JSON.stringify(clue.relatedTo || [])
          );
        }
      }

      // Save NPC relationships
      if (npc.relationships && npc.relationships.length > 0) {
        for (const rel of npc.relationships) {
          const relStmt = database.prepare(`
            INSERT OR REPLACE INTO npc_relationships (
              id, source_id, target_id, target_name, relationship_type,
              attitude, description, history
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
          `);

          const relId = `${npc.id}_${rel.targetName}`;
          relStmt.run(
            relId,
            npc.id,
            rel.targetId || null,
            rel.targetName,
            rel.relationshipType,
            rel.attitude,
            rel.description || null,
            rel.history || null
          );
        }
      }
    }
  }

  /**
   * Save scenarios to database
   */
  private saveScenarios(module: LoadedWorldModule): void {
    const database = this.db.getDatabase();
    const hasMapImagePath = this.db.hasColumn("scenarios", "map_image_path");
    const now = new Date().toISOString();

    const scenarioByName = new Map(
      module.scenarios.map((scenario) => [scenario.name.toLowerCase(), scenario])
    );

    for (const scenario of module.scenarios) {
      const metadata = {
        createdAt: now,
        updatedAt: now,
        source: "world_builder",
        author: "world_builder",
        gameSystem: "CoC 7e",
      };

      const connections = (scenario.connections || []).map((connection) => {
        const targetScenario = scenarioByName.get(connection.scenarioName.toLowerCase());
        return {
          scenarioId: targetScenario?.id || connection.scenarioName,
          relationshipType: connection.relationshipType,
          description: connection.description,
        };
      });

      const scenarioColumns = [
        "scenario_id",
        "name",
        "description",
        "tags",
        "connections",
        "metadata",
        "source_place_id",
      ];
      const scenarioValues: any[] = [
        scenario.id,
        scenario.name,
        scenario.description,
        JSON.stringify(scenario.tags || []),
        JSON.stringify(connections),
        JSON.stringify(metadata),
        scenario.sourcePlaceId || null,
      ];

      if (hasMapImagePath) {
        scenarioColumns.push("map_image_path");
        scenarioValues.push(null);
      }

      const scenarioStmt = database.prepare(
        `INSERT OR REPLACE INTO scenarios (${scenarioColumns.join(", ")}) VALUES (${scenarioColumns
          .map(() => "?")
          .join(", ")})`
      );
      scenarioStmt.run(...scenarioValues);
    }
  }

  /**
   * Save scenario snapshots to database
   */
  private saveDynamicScenarioSnapshots(module: LoadedWorldModule): void {
    const database = this.db.getDatabase();

    for (const [snapshotId, snapshot] of module.scenarioSnapshots.entries()) {
      // Check if snapshot exists
      const existing = database
        .prepare(`SELECT snapshot_id FROM scenario_snapshots WHERE snapshot_id = ?`)
        .get(snapshotId);

      if (existing) {
        continue; // Skip existing snapshots
      }

      // Find corresponding scenario
      const scenario = module.scenarios.find((s) => s.id === snapshot.id || s.name === snapshot.name);
      const scenarioId = scenario?.id || snapshotId;

      // Insert snapshot
      const hasInitialSnapshot = this.db.hasColumn("scenario_snapshots", "initial_snapshot");
      const hasGameTime = this.db.hasColumn("scenario_snapshots", "game_time");

      if (hasInitialSnapshot && hasGameTime) {
        const snapshotStmt = database.prepare(`
          INSERT INTO scenario_snapshots (
            snapshot_id, scenario_id, snapshot_name, location, description,
            events, exits, keeper_notes, time_restriction, show_map,
            initial_snapshot, game_time
          ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        `);

        snapshotStmt.run(
          snapshotId,
          scenarioId,
          snapshot.name,
          snapshot.location,
          snapshot.description,
          JSON.stringify([]), // events removed - tracked via actionResults
          JSON.stringify([]), // exits removed - connections are scenario-level data
          snapshot.keeperNotes || null,
          snapshot.timeRestriction || null,
          snapshot.showMap === false ? 0 : 1,
          (snapshot as any).initialSnapshot ? 1 : 0,
          (snapshot as any).gameTime || null
        );
      } else {
        const snapshotStmt = database.prepare(`
          INSERT INTO scenario_snapshots (
            snapshot_id, scenario_id, snapshot_name, location, description,
            events, exits, keeper_notes, time_restriction, show_map
          ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        `);

        snapshotStmt.run(
          snapshotId,
          scenarioId,
          snapshot.name,
          snapshot.location,
          snapshot.description,
          JSON.stringify([]), // events removed - tracked via actionResults
          JSON.stringify([]), // exits removed - connections are scenario-level data
          snapshot.keeperNotes || null,
          snapshot.timeRestriction || null,
          snapshot.showMap === false ? 0 : 1
        );
      }

      // Insert characters
      if (snapshot.characters && snapshot.characters.length > 0) {
        const charStmt = database.prepare(`
          INSERT OR IGNORE INTO scenario_characters (
            id, snapshot_id, character_name, character_role, character_status,
            character_location, character_notes
          ) VALUES (?, ?, ?, ?, ?, ?, ?)
        `);

        for (const char of snapshot.characters) {
          charStmt.run(
            char.id,
            snapshotId,
            char.name,
            char.role,
            char.status,
            char.location || null,
            char.notes || null
          );
        }
      }

      // Insert clues
      if (snapshot.clues && snapshot.clues.length > 0) {
        const clueStmt = database.prepare(`
          INSERT OR IGNORE INTO scenario_clues (
            clue_id, snapshot_id, clue_text, category, difficulty,
            clue_location, discovery_method, reveals, discovered, discovery_details
          ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        `);

        for (const clue of snapshot.clues) {
          clueStmt.run(
            clue.id,
            snapshotId,
            clue.clueText,
            clue.category,
            clue.difficulty,
            clue.location,
            clue.discoveryMethod || null,
            JSON.stringify(clue.reveals || []),
            clue.discovered ? 1 : 0,
            clue.discoveryDetails ? JSON.stringify(clue.discoveryDetails) : null
          );
        }
      }

      // Insert conditions
      if (snapshot.conditions && snapshot.conditions.length > 0) {
        const conditionStmt = database.prepare(`
          INSERT OR IGNORE INTO scenario_conditions (
            condition_id, snapshot_id, condition_type, description, mechanical_effect
          ) VALUES (?, ?, ?, ?, ?)
        `);

        for (const condition of snapshot.conditions) {
          const conditionId = `${snapshotId}-cond-${Math.random().toString(36).slice(2, 10)}`;
          conditionStmt.run(
            conditionId,
            snapshotId,
            condition.type,
            condition.description,
            condition.mechanicalEffect || null
          );
        }
      }
    }
  }
}
