/**
 * World Module Loader
 * Loads modules generated by the Dynamic World Agent (world builder)
 * Handles the complete world-first module structure with truth timeline, knowledge matrix, etc.
 */

import fs from "fs";
import path from "path";
import type {
  CoCDatabase,
  CoCDatabaseAdapter,
} from "../../shared/agents/memory/database/index.js";
import { getPrismaClient } from "../../shared/agents/memory/database/prismaClient.js";
import {
  resolveEmailId,
  scopeId,
} from "../../shared/agents/memory/database/userContext.js";
import { scopeIdByModule } from "../../shared/agents/memory/database/moduleScope.js";
import type {
  MacroSceneStructure,
  TruthEvent,
  KnowledgeHolder,
  RedHerring,
  MythosEvent,
  EndStateDefinition,
  ScenarioOutline,
  ModuleDigest,
} from "./types.js";
import type { DynamicNPCProfile } from "./types.js";
import type { DynamicScenarioSnapshot } from "./types.js";

/**
 * Complete world module data loaded from all JSON files
 */
export interface LoadedWorldModule {
  moduleName: string;
  moduleDigest: ModuleDigest & { title: string };
  macroScene: MacroSceneStructure;
  mythosEvents: MythosEvent[];
  endState: EndStateDefinition;
  truthTimeline: TruthEvent[];
  knowledgeMatrix: KnowledgeHolder[];
  redHerrings: RedHerring[];
  scenarios: ScenarioOutline[];
  scenarioSnapshots: Map<string, DynamicScenarioSnapshot>; // scenarioId -> snapshot
  npcs: DynamicNPCProfile[];
  files: {
    truthTimelineFile: string;
    knowledgeMatrixFile: string;
    macroSceneFile: string;
    scenariosFile: string;
    moduleDigestFile: string;
    scenariosDir: string;
    npcsDir: string;
  };
}

/**
 * Scenario file payload (array format with single entry)
 */
interface ScenarioFilePayload {
  name: string;
  description: string;
  evidence?: string[];
  clues?: any[];
  snapshot: DynamicScenarioSnapshot;
  tags?: string[];
  connections?: any[];
  npcAssignments?: any[];
}

export class WorldModuleLoader {
  private db: CoCDatabase | CoCDatabaseAdapter;
  private emailId?: string;

  constructor(db: CoCDatabase | CoCDatabaseAdapter, options?: { emailId?: string }) {
    this.db = db;
    this.emailId = options?.emailId;
  }

  private getEmailId(): string | undefined {
    return resolveEmailId(this.emailId);
  }

  private scopeId(id: string): string {
    return scopeId(id, this.getEmailId());
  }

  private scopeByModule(id: string, moduleId: string): string {
    return scopeIdByModule(id, moduleId);
  }

  private scopeArrayByModule(ids: string[] | undefined, moduleId: string): string[] {
    if (!ids) return [];
    return ids.map((id) => this.scopeByModule(id, moduleId));
  }

  /**
   * Check if module directory has changed since last load
   */
  private async checkForChanges(moduleDir: string): Promise<{
    hasChanges: boolean;
    timestamp: number;
  }> {
    const timestampFile = path.join(moduleDir, ".last_world_load_timestamp");
    const currentTime = Date.now();

    // Get all JSON file modification times
    const files = [
      "truth_timeline.json",
      "knowledge_matrix.json",
      "macro_scene.json",
      "scenarios_outline.json",
      "module_digest.json",
    ];

    let latestMtime = 0;
    for (const file of files) {
      const filePath = path.join(moduleDir, file);
      if (fs.existsSync(filePath)) {
        const stats = fs.statSync(filePath);
        latestMtime = Math.max(latestMtime, stats.mtime.getTime());
      }
    }

    // Check NPC and scenario directories
    const npcsDir = path.join(moduleDir, `${path.basename(moduleDir)}_npc`);
    const scenariosDir = path.join(
      moduleDir,
      `${path.basename(moduleDir)}_Scenarios`
    );

    for (const dir of [npcsDir, scenariosDir]) {
      if (fs.existsSync(dir)) {
        const dirFiles = fs.readdirSync(dir).filter((f) => f.endsWith(".json"));
        for (const file of dirFiles) {
          const filePath = path.join(dir, file);
          const stats = fs.statSync(filePath);
          latestMtime = Math.max(latestMtime, stats.mtime.getTime());
        }
      }
    }

    // Check if we have existing data in database
    const emailId = this.getEmailId();
    const prisma = getPrismaClient();

    const existing = await prisma.moduleBackground.findFirst({
      where: {
        title: path.basename(moduleDir),
        ...(emailId ? { emailId } : {}),
      },
      select: { moduleId: true },
    });

    if (!existing) {
      return { hasChanges: true, timestamp: currentTime };
    }

    // Read last load timestamp
    let lastLoadTime = 0;
    if (fs.existsSync(timestampFile)) {
      try {
        lastLoadTime = parseInt(fs.readFileSync(timestampFile, "utf8"));
      } catch {
        return { hasChanges: true, timestamp: currentTime };
      }
    }

    const hasChanges = latestMtime > lastLoadTime;
    return { hasChanges, timestamp: currentTime };
  }

  /**
   * Update the last load timestamp
   */
  private updateLastLoadTimestamp(moduleDir: string, timestamp: number): void {
    const timestampFile = path.join(moduleDir, ".last_world_load_timestamp");
    fs.writeFileSync(timestampFile, timestamp.toString(), "utf8");
  }

  /**
   * Load a complete world module from directory
   */
  async loadWorldModule(
    moduleDir: string,
    forceReload = false
  ): Promise<LoadedWorldModule | null> {
    console.log(`\n=== Loading World Module from: ${moduleDir} ===`);

    if (!fs.existsSync(moduleDir)) {
      console.log(`Directory does not exist: ${moduleDir}`);
      return null;
    }

    const moduleName = path.basename(moduleDir);

    // Check for changes unless forced reload
    if (!forceReload) {
      const { hasChanges } = await this.checkForChanges(moduleDir);
      if (!hasChanges) {
        console.log(
          `No changes detected for module "${moduleName}". Skipping reload.`
        );
        // Could return existing data from database here
        return null;
      }
    }

    console.log(`Loading world module: ${moduleName}`);

    try {
      // 1. Load module digest
      console.log(`  [1/7] Loading module_digest.json...`);
      const moduleDigestFile = path.join(moduleDir, "module_digest.json");
      const moduleDigest = this.loadJSON<ModuleDigest & { title: string }>(
        moduleDigestFile
      );
      console.log(`    Module digest loaded: ${moduleDigest.title}`);

      // 2. Load macro scene (includes mythos events and end state)
      console.log(`  [2/7] Loading macro_scene.json...`);
      const macroSceneFile = path.join(moduleDir, "macro_scene.json");
      const macroSceneData = this.loadJSON<{
        macroScene: MacroSceneStructure;
        mythosEvents: MythosEvent[];
        endState: EndStateDefinition;
      }>(macroSceneFile);
      console.log(
        `    Macro scene loaded: ${macroSceneData.macroScene.locationName}`
      );
      console.log(`    Mythos events: ${macroSceneData.mythosEvents.length}`);

      // 3. Load truth timeline
      console.log(`  [3/7] Loading truth_timeline.json...`);
      const truthTimelineFile = path.join(moduleDir, "truth_timeline.json");
      const truthTimelineData = this.loadJSON<{ truthTimeline: TruthEvent[] }>(
        truthTimelineFile
      );
      console.log(
        `    Truth events: ${truthTimelineData.truthTimeline.length}`
      );

      // 4. Load knowledge matrix and red herrings
      console.log(`  [4/7] Loading knowledge_matrix.json...`);
      const knowledgeMatrixFile = path.join(moduleDir, "knowledge_matrix.json");
      const knowledgeMatrixData = this.loadJSON<{
        knowledgeMatrix: KnowledgeHolder[];
        redHerrings: RedHerring[];
      }>(knowledgeMatrixFile);
      console.log(
        `    Knowledge holders: ${knowledgeMatrixData.knowledgeMatrix.length}`
      );
      console.log(
        `    Red herrings: ${knowledgeMatrixData.redHerrings.length}`
      );

      // 5. Load scenario outlines
      console.log(`  [5/7] Loading scenarios_outline.json...`);
      const scenariosFile = path.join(moduleDir, "scenarios_outline.json");
      const scenariosData = this.loadJSON<{ scenarios: ScenarioOutline[] }>(
        scenariosFile
      );
      console.log(`    Scenario outlines: ${scenariosData.scenarios.length}`);

      // 6. Load scenario snapshots from individual files
      console.log(`  [6/7] Loading scenario snapshots...`);
      const scenariosDir = path.join(moduleDir, `${moduleName}_Scenarios`);
      const scenarioSnapshots = this.loadDynamicScenarioSnapshots(scenariosDir);
      console.log(`    Scenario snapshots loaded: ${scenarioSnapshots.size}`);

      // 7. Load NPCs from individual files
      console.log(`  [7/7] Loading NPCs...`);
      const npcsDir = path.join(moduleDir, `${moduleName}_npc`);
      const npcs = this.loadNPCs(npcsDir);
      console.log(`    NPCs loaded: ${npcs.length}`);

      const loadedModule: LoadedWorldModule = {
        moduleName,
        moduleDigest,
        macroScene: macroSceneData.macroScene,
        mythosEvents: macroSceneData.mythosEvents,
        endState: macroSceneData.endState,
        truthTimeline: truthTimelineData.truthTimeline,
        knowledgeMatrix: knowledgeMatrixData.knowledgeMatrix,
        redHerrings: knowledgeMatrixData.redHerrings,
        scenarios: scenariosData.scenarios,
        scenarioSnapshots,
        npcs,
        files: {
          truthTimelineFile,
          knowledgeMatrixFile,
          macroSceneFile,
          scenariosFile,
          moduleDigestFile,
          scenariosDir,
          npcsDir,
        },
      };

      console.log(`\nWorld module loaded successfully: ${moduleName}`);
      console.log(`   - Truth events: ${loadedModule.truthTimeline.length}`);
      console.log(
        `   - Knowledge holders: ${loadedModule.knowledgeMatrix.length}`
      );
      console.log(`   - Red herrings: ${loadedModule.redHerrings.length}`);
      console.log(`   - Scenarios: ${loadedModule.scenarios.length}`);
      console.log(`   - NPCs: ${loadedModule.npcs.length}`);

      return loadedModule;
    } catch (error) {
      console.error(`Failed to load world module from ${moduleDir}:`, error);
      throw error;
    }
  }

  /**
   * Load and save world module to database
   */
  async loadAndSaveWorldModule(
    moduleDir: string,
    forceReload = false
  ): Promise<LoadedWorldModule | null> {
    const module = await this.loadWorldModule(moduleDir, forceReload);

    if (!module) {
      return null;
    }

    console.log(`\nSaving world module to database: ${module.moduleName}`);

    try {
      // Save to database
      await this.saveToDatabase(module);

      // Update timestamp
      const { timestamp } = await this.checkForChanges(moduleDir);
      this.updateLastLoadTimestamp(moduleDir, timestamp);

      console.log(`World module saved to database: ${module.moduleName}\n`);

      return module;
    } catch (error) {
      console.error(`Failed to save world module to database:`, error);
      throw error;
    }
  }

  /**
   * Load all world modules from Mods directory
   */
  async loadAllWorldModules(forceReload = false): Promise<LoadedWorldModule[]> {
    const modsDir = path.join(process.cwd(), "data", "Mods");

    if (!fs.existsSync(modsDir)) {
      console.log(`Mods directory does not exist: ${modsDir}`);
      return [];
    }

    const moduleDirs = fs.readdirSync(modsDir).filter((dir) => {
      const fullPath = path.join(modsDir, dir);
      return fs.statSync(fullPath).isDirectory();
    });

    console.log(
      `\n=== Loading ${moduleDirs.length} world modules from ${modsDir} ===\n`
    );

    const loadedModules: LoadedWorldModule[] = [];

    for (let i = 0; i < moduleDirs.length; i++) {
      const dir = moduleDirs[i];
      const moduleDir = path.join(modsDir, dir);

      console.log(`[${i + 1}/${moduleDirs.length}] Loading module: ${dir}`);

      try {
        const module = await this.loadAndSaveWorldModule(
          moduleDir,
          forceReload
        );
        if (module) {
          loadedModules.push(module);
        }
      } catch (error) {
        console.error(`  Failed to load module ${dir}:`, error);
      }
    }

    console.log(
      `\n=== Successfully loaded ${loadedModules.length}/${moduleDirs.length} world modules ===\n`
    );

    return loadedModules;
  }

  /**
   * Load JSON file with error handling
   */
  private loadJSON<T>(filePath: string): T {
    if (!fs.existsSync(filePath)) {
      throw new Error(`File not found: ${filePath}`);
    }

    try {
      const content = fs.readFileSync(filePath, "utf8");
      return JSON.parse(content) as T;
    } catch (error) {
      throw new Error(
        `Failed to parse JSON from ${filePath}: ${(error as Error).message}`
      );
    }
  }

  /**
   * Load scenario snapshots from individual scenario files
   */
  private loadDynamicScenarioSnapshots(
    scenariosDir: string
  ): Map<string, DynamicScenarioSnapshot> {
    const snapshots = new Map<string, DynamicScenarioSnapshot>();

    if (!fs.existsSync(scenariosDir)) {
      console.warn(`    Scenarios directory not found: ${scenariosDir}`);
      return snapshots;
    }

    const files = fs
      .readdirSync(scenariosDir)
      .filter((f) => f.endsWith(".json"));

    for (const file of files) {
      try {
        const filePath = path.join(scenariosDir, file);
        const content = fs.readFileSync(filePath, "utf8");
        const data = JSON.parse(content);

        // Handle array format (single entry per file)
        const scenarios: ScenarioFilePayload[] = Array.isArray(data)
          ? data
          : [data];

        for (const scenario of scenarios) {
          if (scenario.snapshot) {
            const snapshot = scenario.snapshot;
            snapshots.set(snapshot.id, snapshot);
          }
        }
      } catch (error) {
        console.warn(`    Failed to load scenario file ${file}:`, error);
      }
    }

    return snapshots;
  }

  /**
   * Load NPCs from individual NPC files
   */
  private loadNPCs(npcsDir: string): DynamicNPCProfile[] {
    const npcs: DynamicNPCProfile[] = [];

    if (!fs.existsSync(npcsDir)) {
      console.warn(`    NPCs directory not found: ${npcsDir}`);
      return npcs;
    }

    const files = fs.readdirSync(npcsDir).filter((f) => f.endsWith(".json"));

    for (const file of files) {
      try {
        const filePath = path.join(npcsDir, file);
        const content = fs.readFileSync(filePath, "utf8");
        const npc = JSON.parse(content) as DynamicNPCProfile;

        // Validate required NPC fields
        if (!npc.id || !npc.name) {
          console.warn(`    Invalid NPC in ${file}: missing id or name`);
          continue;
        }

        npcs.push(npc);
      } catch (error) {
        console.warn(`    Failed to load NPC file ${file}:`, error);
      }
    }

    return npcs;
  }

  /**
   * Save loaded world module to database
   */
  private async saveToDatabase(module: LoadedWorldModule): Promise<void> {
    // 1. Save module background
    console.log(`  [1/4] Saving module background...`);
    const moduleId = await this.saveModuleBackground(module);

    // 2. Save NPCs
    console.log(`  [2/4] Saving ${module.npcs.length} NPCs...`);
    await this.saveNPCs(module.npcs);

    // 3. Save scenarios
    console.log(`  [3/4] Saving ${module.scenarios.length} scenarios...`);
    await this.saveScenarios(module, moduleId);

    // 4. Save scenario snapshots
    console.log(
      `  [4/4] Saving ${module.scenarioSnapshots.size} scenario snapshots...`
    );
    await this.saveDynamicScenarioSnapshots(module, moduleId);

    console.log(`  All data saved to database`);
  }

  /**
   * Save module background to database
   */
  private async saveModuleBackground(module: LoadedWorldModule): Promise<string> {
    const prisma = getPrismaClient();
    const emailId = this.getEmailId();
    const ownerEmailId = emailId || "__system__";
    const normalizedName = module.moduleName.trim().toLowerCase();

    const moduleRow = await prisma.module.upsert({
      where: {
        uq_modules_owner_name_normalized: {
          ownerEmailId,
          moduleNameNormalized: normalizedName,
        },
      },
      update: {
        moduleName: module.moduleName,
        moduleNameNormalized: normalizedName,
        status: "active",
        updatedAt: new Date(),
      },
      create: {
        moduleName: module.moduleName,
        moduleNameNormalized: normalizedName,
        ownerEmailId,
        share: false,
        status: "active",
      },
      select: { moduleId: true, share: true },
    });

    if (emailId) {
      await prisma.modulePermission.upsert({
        where: {
          moduleId_emailId: { moduleId: moduleRow.moduleId, emailId },
        },
        update: {
          role: "owner",
          canPlay: true,
          canManage: true,
          grantedAt: new Date(),
        },
        create: {
          moduleId: moduleRow.moduleId,
          emailId,
          role: "owner",
          canPlay: true,
          canManage: true,
        },
      });
    }
    const moduleId = moduleRow.moduleId;

    // Generate background from macro scene
    const background = `${module.macroScene.locationName} - ${module.macroScene.settingType || "setting"}. ${module.macroScene.economicCore}`;

    // Generate story outline from scenarios
    const storyOutline = module.scenarios
      .map((s, i) => `${i + 1}. ${s.name}: ${s.description}`)
      .join("\n");

    // Get initial game time from first scenario snapshot (usually starting scene)
    let initialGameTime: string | null = null;
    const firstSnapshot = module.scenarioSnapshots.values().next().value;
    if (firstSnapshot?.gameTime) {
      initialGameTime = firstSnapshot.gameTime;
    }

    // Get initial scenario NPCs from starting scene
    const initialScenarioNPCs: string[] = [];
    if (firstSnapshot?.characters) {
      initialScenarioNPCs.push(
        ...firstSnapshot.characters.map((c: any) => c.name)
      );
    }

    // Auto-generate tags
    const tags = [
      "auto-generated",
      "world-builder",
      module.macroScene.settingType || "unknown",
      ...module.mythosEvents.map((e) => e.mythosEntityInvolved.toLowerCase()),
    ];

    await prisma.moduleBackground.upsert({
      where: { moduleId },
      update: {
        title: module.moduleName,
        background,
        storyOutline,
        moduleNotes: module.moduleDigest.moduleNotes,
        keeperGuidance: module.moduleDigest.keeperGuidance,
        moduleLimitations: module.moduleDigest.moduleLimitations,
        initialGameTime,
        initialScenarioNpcs: initialScenarioNPCs,
        introduction: module.moduleDigest.introduction,
        tags,
        emailId: emailId || null,
        truthTimeline: module.truthTimeline as any,
        knowledgeMatrix: module.knowledgeMatrix as any,
        redHerrings: module.redHerrings as any,
        historicalMythos: module.mythosEvents as any,
        endStateDefinition: module.endState as any,
        macroSceneStructure: module.macroScene as any,
        globalTrigger: (module.moduleDigest.globalTrigger || undefined) as any,
        macroMapPath: module.moduleDigest.macroMapPath || null,
      },
      create: {
        moduleId,
        title: module.moduleName,
        background,
        storyOutline,
        moduleNotes: module.moduleDigest.moduleNotes,
        keeperGuidance: module.moduleDigest.keeperGuidance,
        moduleLimitations: module.moduleDigest.moduleLimitations,
        initialGameTime,
        initialScenarioNpcs: initialScenarioNPCs,
        introduction: module.moduleDigest.introduction,
        tags,
        emailId: emailId || null,
        truthTimeline: module.truthTimeline as any,
        knowledgeMatrix: module.knowledgeMatrix as any,
        redHerrings: module.redHerrings as any,
        historicalMythos: module.mythosEvents as any,
        endStateDefinition: module.endState as any,
        macroSceneStructure: module.macroScene as any,
        globalTrigger: (module.moduleDigest.globalTrigger || undefined) as any,
        macroMapPath: module.moduleDigest.macroMapPath || null,
      },
    });

    return moduleId;
  }

  /**
   * Save NPCs to database
   */
  private async saveNPCs(npcs: DynamicNPCProfile[]): Promise<void> {
    const prisma = getPrismaClient();
    const emailId = this.getEmailId();
    const scopedNpcIds = new Set(npcs.map((npc) => this.scopeId(npc.id)));

    // Pass 1: ensure all NPC characters exist before writing dependent rows.
    for (const npc of npcs) {
      const npcId = this.scopeId(npc.id);

      await prisma.character.upsert({
        where: { characterId: npcId },
        update: {
          name: npc.name,
          occupation: npc.occupation || null,
          age: npc.age || null,
          gender: npc.gender || null,
          appearance: npc.appearance || null,
          personality: npc.personality || null,
          background: npc.background || null,
          attributes: npc.attributes,
          status: npc.status,
          skills: npc.skills,
          inventory: npc.inventory as any,
          goals: npc.goals || [],
          secrets: npc.secrets || [],
          notes: npc.notes || null,
          currentLocation: null, // currentLocation removed - location tracked via actionLog
          instantiatedFrom: npc.instantiatedFrom || null,
          inheritsKnowledge: npc.inheritsKnowledge || [],
          emailId: emailId || null,
        },
        create: {
          characterId: npcId,
          name: npc.name,
          occupation: npc.occupation || null,
          age: npc.age || null,
          gender: npc.gender || null,
          appearance: npc.appearance || null,
          personality: npc.personality || null,
          background: npc.background || null,
          attributes: npc.attributes,
          status: npc.status,
          skills: npc.skills,
          inventory: npc.inventory as any,
          goals: npc.goals || [],
          secrets: npc.secrets || [],
          notes: npc.notes || null,
          isNpc: true,
          currentLocation: null, // currentLocation removed - location tracked via actionLog
          instantiatedFrom: npc.instantiatedFrom || null,
          inheritsKnowledge: npc.inheritsKnowledge || [],
          emailId: emailId || null,
        },
      });
    }

    // Pass 2: save clues (depends on NPC character existing).
    for (const npc of npcs) {
      const npcId = this.scopeId(npc.id);

      if (npc.clues && npc.clues.length > 0) {
        for (const clue of npc.clues) {
          const clueId = this.scopeId(clue.id);

          await prisma.npcClue.upsert({
            where: { id: clueId },
            update: {
              npcId: npcId,
              clueText: clue.clueText,
              category: clue.category || null,
              difficulty: clue.difficulty || null,
              revealed: clue.revealed ? true : false,
              relatedTo: clue.relatedTo || [],
              emailId: emailId || null,
            },
            create: {
              id: clueId,
              npcId: npcId,
              clueText: clue.clueText,
              category: clue.category || null,
              difficulty: clue.difficulty || null,
              revealed: clue.revealed ? true : false,
              relatedTo: clue.relatedTo || [],
              emailId: emailId || null,
            },
          });
        }
      }
    }

    // Collect relationship targets that are not in this NPC batch.
    const externalTargetIds = new Set<string>();
    for (const npc of npcs) {
      if (!npc.relationships || npc.relationships.length === 0) continue;
      for (const rel of npc.relationships) {
        const rawTargetId =
          typeof rel.targetId === "string" ? rel.targetId.trim() : "";
        if (!rawTargetId) continue;
        const scopedTargetId = this.scopeId(rawTargetId);
        if (!scopedNpcIds.has(scopedTargetId)) {
          externalTargetIds.add(scopedTargetId);
        }
      }
    }

    const existingExternalTargetIds = new Set<string>();
    if (externalTargetIds.size > 0) {
      const existingTargets = await prisma.character.findMany({
        where: { characterId: { in: Array.from(externalTargetIds) } },
        select: { characterId: true },
      });
      for (const row of existingTargets) {
        existingExternalTargetIds.add(row.characterId);
      }
    }

    // Pass 3: save relationships (requires source and target characters to exist).
    let skippedRelationships = 0;
    for (const npc of npcs) {
      const npcId = this.scopeId(npc.id);

      if (npc.relationships && npc.relationships.length > 0) {
        for (const rel of npc.relationships) {
          const rawTargetId =
            typeof rel.targetId === "string" ? rel.targetId.trim() : "";
          if (!rawTargetId) {
            skippedRelationships++;
            console.warn(
              `[WorldModuleLoader] Skip relationship with empty targetId: ${npc.name} -> ${rel.targetName || "unknown"}`
            );
            continue;
          }
          const targetId = this.scopeId(rawTargetId);
          const targetExists =
            scopedNpcIds.has(targetId) ||
            existingExternalTargetIds.has(targetId);
          if (!targetExists) {
            skippedRelationships++;
            console.warn(
              `[WorldModuleLoader] Skip relationship, target character not found: ${npc.name} -> ${rel.targetName} (${targetId})`
            );
            continue;
          }

          const relId = this.scopeId(`${npc.id}_${rel.targetName}`);

          await prisma.npcRelationship.upsert({
            where: { id: relId },
            update: {
              sourceId: npcId,
              targetId,
              targetName: rel.targetName,
              relationshipType: rel.relationshipType,
              attitude: rel.attitude,
              description: rel.description || null,
              history: rel.history || null,
              emailId: emailId || null,
            },
            create: {
              id: relId,
              sourceId: npcId,
              targetId,
              targetName: rel.targetName,
              relationshipType: rel.relationshipType,
              attitude: rel.attitude,
              description: rel.description || null,
              history: rel.history || null,
              emailId: emailId || null,
            },
          });
        }
      }
    }

    if (skippedRelationships > 0) {
      console.warn(
        `[WorldModuleLoader] Skipped ${skippedRelationships} unresolved NPC relationships`
      );
    }
  }

  /**
   * Save scenarios to database
   */
  private async saveScenarios(
    module: LoadedWorldModule,
    moduleId: string
  ): Promise<void> {
    const prisma = getPrismaClient();
    const now = new Date().toISOString();

    const scenarioByName = new Map(
      module.scenarios.map((scenario) => [
        scenario.name.toLowerCase(),
        scenario,
      ])
    );

    for (const scenario of module.scenarios) {
      const scopedScenarioId = this.scopeByModule(scenario.id, moduleId);
      const metadata = {
        createdAt: now,
        updatedAt: now,
        source: "world_builder",
        author: "world_builder",
        gameSystem: "CoC 7e",
      };

      const connections = (scenario.connections || []).map((connection) => {
        const targetScenario = scenarioByName.get(
          connection.scenarioName.toLowerCase()
        );
        const targetScenarioId = targetScenario
          ? this.scopeByModule(targetScenario.id, moduleId)
          : null;
        return {
          scenarioId: targetScenarioId || connection.scenarioName,
          relationshipType: connection.relationshipType,
          description: connection.description,
        };
      });

      await prisma.scenario.upsert({
        where: {
          moduleId_scenarioId: {
            moduleId,
            scenarioId: scopedScenarioId,
          },
        },
        update: {
          moduleId,
          name: scenario.name,
          description: scenario.description,
          tags: scenario.tags || [],
          connections,
          metadata,
          sourcePlaceId: scenario.sourcePlaceId || null,
          mapImagePath: null,
        },
        create: {
          scenarioId: scopedScenarioId,
          moduleId,
          name: scenario.name,
          description: scenario.description,
          tags: scenario.tags || [],
          connections,
          metadata,
          sourcePlaceId: scenario.sourcePlaceId || null,
          mapImagePath: null,
        },
      });
    }
  }

  /**
   * Save scenario snapshots to database
   */
  private async saveDynamicScenarioSnapshots(
    module: LoadedWorldModule,
    moduleId: string
  ): Promise<void> {
    const prisma = getPrismaClient();

    for (const [snapshotId, snapshot] of module.scenarioSnapshots.entries()) {
      const scopedSnapshotId = this.scopeByModule(snapshotId, moduleId);

      // Check if snapshot exists
      const existing = await prisma.scenarioSnapshot.findFirst({
        where: { snapshotId: scopedSnapshotId },
        select: { snapshotId: true },
      });

      if (existing) {
        continue; // Skip existing snapshots
      }

      // Find corresponding scenario
      const scenario = module.scenarios.find(
        (s) => s.id === snapshot.id || s.name === snapshot.name
      );
      const scenarioId = scenario?.id || snapshotId;
      const scopedScenarioId = this.scopeByModule(scenarioId, moduleId);

      const sceneImagePath = (snapshot as any).sceneImage?.path || null;

      // Insert snapshot
      await prisma.scenarioSnapshot.create({
        data: {
          snapshotId: scopedSnapshotId,
          scenarioId: scopedScenarioId,
          moduleId,
          snapshotName: snapshot.name,
          location: snapshot.location,
          description: snapshot.description,
          events: [], // events removed - tracked via actionResults
          exits: [], // exits removed - connections are scenario-level data
          keeperNotes: snapshot.keeperNotes || null,
          timeRestriction: snapshot.timeRestriction || null,
          showMap: snapshot.showMap !== false,
          initialSnapshot: (snapshot as any).initialSnapshot ? true : false,
          gameTime: (snapshot as any).gameTime || null,
          sceneImagePath,
        },
      });

      // Insert characters
      if (snapshot.characters && snapshot.characters.length > 0) {
        for (const char of snapshot.characters) {
          const rawCharId =
            char.id ||
            `${scopedSnapshotId}-char-${Math.random().toString(36).slice(2, 10)}`;
          const scopedCharId = this.scopeByModule(rawCharId, moduleId);

          try {
            await prisma.scenarioCharacter.create({
              data: {
                id: scopedCharId,
                snapshotId: scopedSnapshotId,
                moduleId,
                characterName: char.name,
                characterRole: char.role,
                characterStatus: char.status,
                characterLocation: char.location || null,
                characterNotes: char.notes || null,
              },
            });
          } catch (error: any) {
            // P2002: Unique constraint violation - ignore duplicates
            if (error?.code !== "P2002") {
              throw error;
            }
          }
        }
      }

      // Insert clues
      if (snapshot.clues && snapshot.clues.length > 0) {
        for (const clue of snapshot.clues) {
          const scopedClueId = this.scopeByModule(clue.id, moduleId);

          try {
            await prisma.scenarioClue.create({
              data: {
                clueId: scopedClueId,
                snapshotId: scopedSnapshotId,
                moduleId,
                clueText: clue.clueText,
                category: clue.category,
                difficulty: clue.difficulty,
                clueLocation: clue.location,
                discoveryMethod: clue.discoveryMethod || null,
                reveals: this.scopeArrayByModule(clue.reveals || [], moduleId),
                discovered: clue.discovered ? true : false,
                discoveryDetails: (clue.discoveryDetails || undefined) as any,
              },
            });
          } catch (error: any) {
            // P2002: Unique constraint violation - ignore duplicates
            if (error?.code !== "P2002") {
              throw error;
            }
          }
        }
      }

      // Insert conditions
      if (snapshot.conditions && snapshot.conditions.length > 0) {
        for (const condition of snapshot.conditions) {
          const conditionId = `${scopedSnapshotId}-cond-${Math.random().toString(36).slice(2, 10)}`;

          try {
            await prisma.scenarioCondition.create({
              data: {
                conditionId,
                snapshotId: scopedSnapshotId,
                moduleId,
                conditionType: condition.type,
                description: condition.description,
                mechanicalEffect: condition.mechanicalEffect || null,
              },
            });
          } catch (error: any) {
            // P2002: Unique constraint violation - ignore duplicates
            if (error?.code !== "P2002") {
              throw error;
            }
          }
        }
      }
    }
  }
}
