// src/engine/actions/types.ts
//
// Tool-driven action engine contracts (plan 2026-08-26). One structured `act`
// Tool expresses character intent; the Engine owns acceptance, lifecycle,
// timing and outcomes. There is deliberately NO action-kind discriminator
// anywhere in these types — all open-ended actions share one command shape,
// one resolution rule set and one WorldDelta schema.

import type { CharacterPosition } from "../../state/topologyTypes.js";
import type {
  CharacterCondition,
  ConditionPredicate,
  EntityKind,
  GameTime,
  SceneCondition,
} from "../core/types.js";

/** Bumped whenever a persisted ActionCommand / EngineAction shape changes
 *  incompatibly. Snapshots carrying a different version are rejected outright
 *  (decision 2026-08-26: no legacy-snapshot compatibility). */
export const ACTION_SCHEMA_VERSION = 1;

// ==================== Agent-facing references ====================

export const ACTION_ENTITY_KINDS = ["character", "item", "scene"] as const;
export type ActionEntityKind = (typeof ACTION_ENTITY_KINDS)[number];

export interface ActionEntityRef {
  kind: ActionEntityKind;
  id: string;
}

export const OBJECT_REF_ROLES = [
  "target",
  "tool",
  "destination",
  "recipient",
] as const;
export type ObjectRefRole = (typeof OBJECT_REF_ROLES)[number];

/** How the actor intends to use the referenced entity. The role never limits
 *  which entities the Engine may end up modifying. */
export interface ActionObjectRef extends ActionEntityRef {
  role?: ObjectRefRole;
}

// ==================== Agent tool args (untrusted) ====================

/** Raw arguments of the single `act` Tool as produced by the model. Untrusted:
 *  the trust boundary (commandBuilder/commandValidator) turns these into an
 *  `ActionCommand`. Contains only intent fields — never envelope fields, skill
 *  values, difficulties, rolls or outcomes. */
export interface ActToolArgs {
  description: string;
  objectRefs: ActionObjectRef[];
  /** Actor's proposed commitment/estimate in ticks. Intent only — the Engine
   *  decides the authoritative `resolvedDurationTicks`. */
  proposedDurationTicks: number;
  /** Skill the actor consciously employs. Any known CoC skill name is
   *  acceptable (trained value from the profile, base value otherwise). */
  skillId?: string;
  /** Which tongue, required when `skillId` is "Languages" and meaningless
   *  otherwise. */
  language?: string;
  /** Exact words spoken, verbatim. Omitted for silent actions. */
  utterance?: string;
}

// ==================== Trusted command ====================

/** Fields the model must never author. Generated by the controller from
 *  current Engine/DGSM state, preventing forged actor, place or time. */
export interface TrustedActionEnvelope {
  commandId: string;
  actorId: string;
  issuedAt: GameTime;
  issuedSceneId: string;
  /** Set when the actor had a live action at submit time. The old action is
   *  NOT cancelled eagerly — both enter the next tick resolution together
   *  (interrupted transition + new start resolved on one snapshot). */
  replacesActionId?: string;
}

export interface ActionCommand extends TrustedActionEnvelope {
  description: string;
  utterance?: string;
  objectRefs: ActionObjectRef[];
  /** Role-proposed commitment/estimate; Engine may accept, shorten or extend. */
  proposedDurationTicks: number;
  /** Copied from the tool's `skillId` after validation — the name only. This
   *  is the skill that gets checked; the Engine sets its difficulty when the
   *  action starts and code rolls it when the action's time is spent. */
  declaredSkillId?: string;
  /** Which tongue, when `declaredSkillId` is "Languages". Set only for a
   *  language the actor has actually learned: a native tongue needs no skill
   *  and the boundary drops the declaration entirely. */
  declaredLanguage?: string;
  /** Never set at intake. Kept for snapshots written before dice moved to
   *  resolution time; the live roll lives on `EngineAction.checkOutcome`. */
  skillRoll?: SkillRollRecord;
}

/** Intake answer to a submitted command. A receipt, not a world outcome. */
export interface ActionReceipt {
  accepted: boolean;
  actionId?: string;
  status: "queued" | "rejected";
  reason?: string;
}

// ==================== Skill roll & judgement ====================

export const SKILL_SUCCESS_LEVELS = [
  "critical",
  "extreme",
  "hard",
  "regular",
  "failure",
  "fumble",
] as const;
export type SkillSuccessLevel = (typeof SKILL_SUCCESS_LEVELS)[number];

/** Immutable record of the single actor roll made at command creation.
 *  `skillValue` is the real value read from character state at submit time —
 *  the actor never supplies it. */
export interface SkillRollRecord {
  rollId: string;
  skillId: string;
  /** The value actually rolled against — after any condition penalties. */
  skillValue: number;
  /** The value before those penalties, present only when they changed it.
   *  `skillValue` is rendered to the Engine inside the action's `diceRoll`,
   *  so carrying the unpenalized number alongside is what makes a surprising
   *  roll explicable in the log and in the Engine's context. */
  skillValueBase?: number;
  roll: number;
  successLevel: SkillSuccessLevel;
}

export type ActionOutcome =
  | "success"
  | "partial"
  | "failure"
  | "blocked"
  | "continue";

/** Engine-owned verdict on one action. `direct` when no skill was declared
 *  (no hidden roll ever happens); `skill_assessed` when a roll already exists
 *  and the Engine judges applicability, required level and final outcome. */
export type ActionJudgement =
  | {
      kind: "direct";
      outcome: ActionOutcome;
      reason: string;
    }
  | {
      kind: "skill_assessed";
      skillId: string;
      rollId: string;
      applicability: "accepted" | "rejected";
      requiredLevel?: "regular" | "hard" | "extreme";
      checkType?: "single" | "opposed";
      targetIds: string[];
      opposedDefenseIds?: string[];
      outcome: ActionOutcome;
      reason: string;
    };

// ==================== Engine action lifecycle ====================

export type EngineActionStatus =
  | "queued"
  | "active"
  | "completed"
  | "failed"
  | "interrupted"
  | "cancelled";

/** Persisted first-class action state. No pre-generated planned outcome:
 *  in-flight actions are resolved against the latest snapshot when they come
 *  due, are affected, or are replaced. */
export interface EngineAction {
  id: string;
  command: ActionCommand;
  status: EngineActionStatus;
  submittedAt: GameTime;
  startedAt?: GameTime;
  lastAdvancedAt?: GameTime;
  progressMinutes: number;
  /** Engine-owned authoritative duration decided from the action and world
   *  state. Never copied from `proposedDurationTicks` without judgement. */
  resolvedDurationTicks?: number;
  nextWakeAt?: GameTime;
  /** The bar the Engine set when this action started, before any roll
   *  existed. Immutable once written. */
  check?: {
    skillId: string;
    /** Carried through from the command so the roll finds the right fluency:
     *  "Languages" is a domain, not a number. */
    language?: string;
    requiredLevel: "regular" | "hard" | "extreme";
    basis: string;
    /** Who resists and with what, when the Engine named an opposition. */
    opposedBy?: Array<{ characterId: string; skillId: string }>;
  };
  /** Filled by code when the action resolves: the roll made against
   *  `check`, and the deterministic verdict. Never re-rolled — retries and
   *  rehydration reuse this record. */
  checkOutcome?: ResolvedCheck;
  /** JSON-safe data only (no closures, Maps or class instances) — this field
   *  round-trips through snapshot serialization verbatim. */
  runtime?: Record<string, unknown>;
}

/** What code rolled and what it means. Handed to the Engine as INPUT on the
 *  resolving call — it never chooses this, and its resolution must be
 *  consistent with it. */
export interface ResolvedCheck {
  actor: SkillRollRecord;
  requiredLevel: "regular" | "hard" | "extreme";
  /** Defender rolls, when the Engine named an opposition. */
  defenders?: Array<{
    characterId: string;
    record: SkillRollRecord;
    /** Actor wins strictly higher rank; the defender wins ties. */
    actorWon: boolean;
  }>;
  /** Did the action clear the bar (and beat every defender)? */
  met: boolean;
  /** A fumble is never met, and licenses a worse outcome than a plain miss. */
  fumble: boolean;
}

export interface ActionTransition {
  actionId: string;
  actorId: string;
  from: EngineActionStatus;
  /** Derived by code, never declared by the Engine: a result block ends the
   *  action (completed when its duration was spent, interrupted when it was
   *  cut short); silence keeps it active. */
  to: EngineActionStatus;
  /** Minutes the clock actually advanced for this action since it was last
   *  touched. Computed from the clock — the Engine has no say. */
  progressDeltaMinutes: number;
  /** Set or revised only by the Engine; never an authoritative Tool result. */
  resolvedDurationTicks?: number;
  timingReason?: string;
  nextWakeAt?: GameTime;
  reason?: string;
  /** Set when this transition is a movement that never started because the
   *  stated route did not join up. `reason` says it in the engine's words for
   *  the log; these two ids let the actor be told which pair of places their
   *  remembered way ran between, in theirs. */
  unstatedHop?: { fromId: string; toId: string };
}

// ==================== World deltas ====================

export type CharacterStateOperation =
  | { kind: "hp"; delta: number; reason: string }
  | { kind: "san"; delta: number; reason: string }
  | { kind: "fatigue"; delta: number; reason: string }
  | { kind: "position"; position: CharacterPosition }
  /**
   * Where they now are WITHIN their location, as prose. Empty string clears
   * it; a location change clears it in code, without being asked.
   */
  | { kind: "spot"; spot: string }
  | { kind: "addCondition"; condition: CharacterCondition }
  | { kind: "removeCondition"; conditionId: string };

export type SceneStateOperation =
  | { kind: "addCondition"; condition: SceneCondition }
  | { kind: "removeCondition"; predicate: ConditionPredicate }
  | {
      /** Rewrite the place's whole prose. Descriptions and references are
       *  deliberately decoupled: rewriting the prose neither adds nor removes
       *  any entity — it changes what a visitor is told about the place. */
      kind: "setDescription";
      description: string;
    }
  | {
      kind: "connectionBlock";
      connectionId: string;
      blocked: boolean;
      reason: string;
    }
  | {
      /** These characters have found a concealed passage. Addressed at the
       *  connection because that is where the fact lives — `discoveredBy`
       *  sits beside `hidden` on the passage itself — and it takes a list
       *  because finding is not private: everyone who watched the bookcase
       *  swing out learned the same thing at the same moment. */
      kind: "connectionDiscovered";
      connectionId: string;
      characterIds: string[];
    }
  | {
      /** Reveal (`hidden: false`) or conceal a connection by its authored id. */
      kind: "connectionHidden";
      connectionId: string;
      hidden: boolean;
    }
  | {
      kind: "environmentContribute";
      quantity: "temperature" | "illumination" | "oxygen" | "noise";
      value: number;
    }
  | { kind: "environmentHazard"; add?: string[]; remove?: string[] };

/** `create` · `move` · `destroy` answer WHERE an item is and WHETHER it is —
 *  structural, because perception lists the ids held by a place or a pocket and
 *  the citation boundary accepts exactly those. `set` answers what it is LIKE,
 *  which is its description plus the two lighting numbers a deterministic
 *  subsystem reads. It replaced `modify` and `damage`: damage was only ever a
 *  sentence appended to a description, and had no way to put out the lamp it
 *  had just smashed. */
export type ItemStateOperation =
  | {
      kind: "create";
      name: string;
      location: string;
      description?: string;
      /** Stable id, used verbatim when unused. Non-Latin names collapse to
       *  nothing under the generated-id slug, so those must pass one. */
      id?: string;
    }
  | { kind: "move"; from: string; to: string }
  | { kind: "destroy" }
  | {
      kind: "set";
      /** Replaces the description wholesale. */
      description?: string;
      /** Adds one sentence to the description instead of replacing it. */
      appendDescription?: string;
      /** Conceal from / reveal to characters. `false` is the reveal. */
      hidden?: boolean;
      isLightSource?: boolean;
      lightLevel?: number;
    };

export type CharacterChange = {
  domain: "character";
  characterId: string;
  operation: CharacterStateOperation;
};

export type SceneChange = {
  domain: "scene";
  sceneId: string;
  operation: SceneStateOperation;
};

export type ItemChange = {
  domain: "item";
  /** Absent only for `create` (the item does not exist yet). */
  itemId?: string;
  operation: ItemStateOperation;
};

export type WorldDelta = CharacterChange | SceneChange | ItemChange;

export type WorldDeltaSource =
  | { kind: "action"; actionId: string }
  | { kind: "subsystem"; subsystemId: string }
  | { kind: "scriptedEvent"; eventId: string };

export interface SourcedWorldDelta<T extends WorldDelta = WorldDelta> {
  source: WorldDeltaSource;
  /** Short statement of why this action/event produces this change. Audited;
   *  the validator rejects deltas it cannot causally tie to an input. */
  causalBasis: string;
  delta: T;
}

// ==================== Occurrences ====================

export type SignalChannel = "visual" | "sound" | "smell" | "touch" | "direct";

/** Objective thing that happened this tick — not necessarily persisted as
 *  state (speech, a gunshot, a failed lockpick slipping). Facts use world-true
 *  references, never per-character perspective wording. */
export interface Occurrence {
  id: string;
  tickId: string;
  sourceActionIds: string[];
  locationId?: string;
  facts: Array<{
    id: string;
    type: string;
    content: string;
    /** Engine vocabulary, not the actor citation grammar: an occurrence may
     *  reference a connection edge ("the pass is blocked") even though actors
     *  cannot cite one — such a ref renders untagged. */
    entityRefs: Array<{ kind: EntityKind; id: string }>;
  }>;
  participants: Array<{
    characterId: string;
    role: "actor" | "target" | "directly_affected";
  }>;
  /** Characters physically/sensorially able to perceive this occurrence.
   *  The Engine lists IDs only; what each one actually perceives is the
   *  Renderer's job. */
  perceiverCharacterIds: string[];
  signals: Array<{
    factIds: string[];
    channel: SignalChannel;
    originLocationId?: string;
    intensity?: number;
  }>;
}

// ==================== Tick resolution output ====================

export interface TickResolution {
  transitions: ActionTransition[];
  characterChanges: SourcedWorldDelta<CharacterChange>[];
  sceneChanges: SourcedWorldDelta<SceneChange>[];
  itemChanges: SourcedWorldDelta<ItemChange>[];
  occurrences: Occurrence[];
}
