// src/engine/actions/types.ts
//
// Tool-driven action engine contracts (plan 2026-08-26). One structured `act`
// Tool expresses character intent; the Engine owns acceptance, lifecycle,
// timing and outcomes. There is deliberately NO action-kind discriminator
// anywhere in these types — all open-ended actions share one command shape,
// one resolution rule set and one WorldDelta schema.

import type { CharacterPosition } from "../../state/topologyTypes.js";
import type {
  CharacterCondition,
  ConditionPredicate,
  GameTime,
  SceneCondition,
} from "../core/types.js";

/** Bumped whenever a persisted ActionCommand / EngineAction shape changes
 *  incompatibly. Snapshots carrying a different version are rejected outright
 *  (decision 2026-08-26: no legacy-snapshot compatibility). */
export const ACTION_SCHEMA_VERSION = 1;

// ==================== Agent-facing references ====================

export const ACTION_ENTITY_KINDS = ["character", "item", "scene"] as const;
export type ActionEntityKind = (typeof ACTION_ENTITY_KINDS)[number];

export interface ActionEntityRef {
  kind: ActionEntityKind;
  id: string;
}

export const OBJECT_REF_ROLES = [
  "target",
  "tool",
  "destination",
  "recipient",
] as const;
export type ObjectRefRole = (typeof OBJECT_REF_ROLES)[number];

/** How the actor intends to use the referenced entity. The role never limits
 *  which entities the Engine may end up modifying. */
export interface ActionObjectRef extends ActionEntityRef {
  role?: ObjectRefRole;
}

// ==================== Agent tool args (untrusted) ====================

/** Raw arguments of the single `act` Tool as produced by the model. Untrusted:
 *  the trust boundary (commandBuilder/commandValidator) turns these into an
 *  `ActionCommand`. Contains only intent fields — never envelope fields, skill
 *  values, difficulties, rolls or outcomes. */
export interface ActToolArgs {
  description: string;
  objectRefs: ActionObjectRef[];
  /** Actor's proposed commitment/estimate in ticks. Intent only — the Engine
   *  decides the authoritative `resolvedDurationTicks`. */
  proposedDurationTicks: number;
  /** Skill the actor consciously employs. Any known CoC skill name is
   *  acceptable (trained value from the profile, base value otherwise). */
  skillId?: string;
  /** Exact words spoken, verbatim. Omitted for silent actions. */
  utterance?: string;
}

// ==================== Trusted command ====================

/** Fields the model must never author. Generated by the controller from
 *  current Engine/DGSM state, preventing forged actor, place or time. */
export interface TrustedActionEnvelope {
  commandId: string;
  actorId: string;
  issuedAt: GameTime;
  issuedSceneId: string;
  /** Set when the actor had a live action at submit time. The old action is
   *  NOT cancelled eagerly — both enter the next tick resolution together
   *  (interrupted transition + new start resolved on one snapshot). */
  replacesActionId?: string;
}

export interface ActionCommand extends TrustedActionEnvelope {
  description: string;
  utterance?: string;
  objectRefs: ActionObjectRef[];
  /** Role-proposed commitment/estimate; Engine may accept, shorten or extend. */
  proposedDurationTicks: number;
  /** Copied from the tool's `skillId` after validation. Must be present iff
   *  `skillRoll` is present. */
  declaredSkillId?: string;
  /** Trusted and immutable; generated by code the moment the command is built
   *  when `declaredSkillId` exists. Retries reuse it — never re-rolled. */
  skillRoll?: SkillRollRecord;
}

/** Intake answer to a submitted command. A receipt, not a world outcome. */
export interface ActionReceipt {
  accepted: boolean;
  actionId?: string;
  status: "queued" | "rejected";
  reason?: string;
}

// ==================== Skill roll & judgement ====================

export const SKILL_SUCCESS_LEVELS = [
  "critical",
  "extreme",
  "hard",
  "regular",
  "failure",
  "fumble",
] as const;
export type SkillSuccessLevel = (typeof SKILL_SUCCESS_LEVELS)[number];

/** Immutable record of the single actor roll made at command creation.
 *  `skillValue` is the real value read from character state at submit time —
 *  the actor never supplies it. */
export interface SkillRollRecord {
  rollId: string;
  skillId: string;
  skillValue: number;
  roll: number;
  successLevel: SkillSuccessLevel;
}

export type ActionOutcome =
  | "success"
  | "partial"
  | "failure"
  | "blocked"
  | "continue";

/** Engine-owned verdict on one action. `direct` when no skill was declared
 *  (no hidden roll ever happens); `skill_assessed` when a roll already exists
 *  and the Engine judges applicability, required level and final outcome. */
export type ActionJudgement =
  | {
      kind: "direct";
      outcome: ActionOutcome;
      reason: string;
    }
  | {
      kind: "skill_assessed";
      skillId: string;
      rollId: string;
      applicability: "accepted" | "rejected";
      requiredLevel?: "regular" | "hard" | "extreme";
      checkType?: "single" | "opposed";
      targetIds: string[];
      opposedDefenseIds?: string[];
      outcome: ActionOutcome;
      reason: string;
    };

// ==================== Engine action lifecycle ====================

export type EngineActionStatus =
  | "queued"
  | "active"
  | "completed"
  | "failed"
  | "interrupted"
  | "cancelled";

/** Persisted first-class action state. No pre-generated planned outcome:
 *  in-flight actions are resolved against the latest snapshot when they come
 *  due, are affected, or are replaced. */
export interface EngineAction {
  id: string;
  command: ActionCommand;
  status: EngineActionStatus;
  submittedAt: GameTime;
  startedAt?: GameTime;
  lastAdvancedAt?: GameTime;
  progressMinutes: number;
  /** Engine-owned authoritative duration decided from the action and world
   *  state. Never copied from `proposedDurationTicks` without judgement. */
  resolvedDurationTicks?: number;
  nextWakeAt?: GameTime;
  /** JSON-safe data only (no closures, Maps or class instances) — this field
   *  round-trips through snapshot serialization verbatim. */
  runtime?: Record<string, unknown>;
}

export interface ActionTransition {
  actionId: string;
  actorId: string;
  from: EngineActionStatus;
  to: EngineActionStatus;
  progressDeltaMinutes: number;
  /** Set or revised only by the Engine; never an authoritative Tool result. */
  resolvedDurationTicks?: number;
  timingReason?: string;
  nextWakeAt?: GameTime;
  reason?: string;
}

// ==================== World deltas ====================

export type CharacterStateOperation =
  | { kind: "hp"; delta: number; reason: string }
  | { kind: "san"; delta: number; reason: string }
  | { kind: "fatigue"; delta: number; reason: string }
  | { kind: "position"; position: CharacterPosition }
  | { kind: "addCondition"; condition: CharacterCondition }
  | { kind: "removeCondition"; conditionId: string }
  | { kind: "relationship"; toCharacterId: string; delta?: number; note?: string };

export type SceneStateOperation =
  | { kind: "addCondition"; condition: SceneCondition }
  | { kind: "removeCondition"; predicate: ConditionPredicate }
  | {
      kind: "connectionBlock";
      connectionId: string;
      blocked: boolean;
      reason: string;
    }
  | {
      kind: "environmentContribute";
      quantity: "temperature" | "illumination" | "oxygen" | "noise";
      value: number;
    }
  | { kind: "environmentHazard"; add?: string[]; remove?: string[] };

export type ItemStateOperation =
  | { kind: "create"; name: string; location: string; properties?: Record<string, unknown> }
  | { kind: "move"; from: string; to: string }
  | { kind: "modify"; description: string }
  | { kind: "damage"; damagedBy: string; reason: string }
  | { kind: "destroy" };

export type CharacterChange = {
  domain: "character";
  characterId: string;
  operation: CharacterStateOperation;
};

export type SceneChange = {
  domain: "scene";
  sceneId: string;
  operation: SceneStateOperation;
};

export type ItemChange = {
  domain: "item";
  /** Absent only for `create` (the item does not exist yet). */
  itemId?: string;
  operation: ItemStateOperation;
};

export type WorldDelta = CharacterChange | SceneChange | ItemChange;

export type WorldDeltaSource =
  | { kind: "action"; actionId: string }
  | { kind: "subsystem"; subsystemId: string }
  | { kind: "scriptedEvent"; eventId: string };

export interface SourcedWorldDelta<T extends WorldDelta = WorldDelta> {
  source: WorldDeltaSource;
  /** Short statement of why this action/event produces this change. Audited;
   *  the validator rejects deltas it cannot causally tie to an input. */
  causalBasis: string;
  delta: T;
}

// ==================== Occurrences ====================

export type SignalChannel = "visual" | "sound" | "smell" | "touch" | "direct";

/** Objective thing that happened this tick — not necessarily persisted as
 *  state (speech, a gunshot, a failed lockpick slipping). Facts use world-true
 *  references, never per-character perspective wording. */
export interface Occurrence {
  id: string;
  tickId: string;
  sourceActionIds: string[];
  locationId?: string;
  facts: Array<{
    id: string;
    type: string;
    content: string;
    entityRefs: ActionEntityRef[];
  }>;
  participants: Array<{
    characterId: string;
    role: "actor" | "target" | "directly_affected";
  }>;
  /** Characters physically/sensorially able to perceive this occurrence.
   *  The Engine lists IDs only; what each one actually perceives is the
   *  Renderer's job. */
  perceiverCharacterIds: string[];
  signals: Array<{
    factIds: string[];
    channel: SignalChannel;
    originLocationId?: string;
    intensity?: number;
  }>;
}

// ==================== Tick resolution output ====================

export interface TickResolution {
  transitions: ActionTransition[];
  characterChanges: SourcedWorldDelta<CharacterChange>[];
  sceneChanges: SourcedWorldDelta<SceneChange>[];
  itemChanges: SourcedWorldDelta<ItemChange>[];
  occurrences: Occurrence[];
}
